### ISSUE TITLE
Make webhook mechanical information less hidden

### ISSUE THREAD

**Issue by tomczoink** [ably/docs#1030]
Currently the webhook mechanics are hidden away in a minimised section, which can make it quite hard to discover. This is a bit problematic as it's pretty important for using our webhook offering for our customers to know. https://www.ably.io/documentation/general/events#batching.

We should look to remove them from the minimised sections.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/DOC-256) by [Unito](https://www.unito.io/learn-more)

**Comment by tbedford** [comment]
Modified to include unminimizing all minimzed sections.
