### ISSUE TITLE
History page doesn't have information about long term persistence of last message

### ISSUE THREAD

**Issue by kavalerov** [ably/docs#1031]
- content incorrect

**Description of issue:**

We need to add information about the long-term persistence of last messages here

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/EDU-257) by [Unito](https://www.unito.io)

**Comment by kavalerov** [comment]
This was about https://www.ably.io/documentation/core-features/history , sorry.

**Comment by kavalerov** [comment]
However, the problem is that this is not supported in History API....

**Comment by kavalerov** [comment]
@ginotoro @Ugbot this is what we were discussing on a call today.

**Comment by tbedford** [comment]
We do have "persist last message" documented [here](https://ably.com/documentation/realtime/channels/channel-parameters/rewind#state-persistence) and [here](https://ably.com/documentation/general/channel-rules-namespaces/). However, its name was changed to "state persistence".
