### ISSUE TITLE
Spec: Add requirement that any use provided callback exception must be caught, logged, and continue

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#108]
A customer noticed that in the Ruby library an exception in the subscribe callback results in the library crashing which is not intended.

However, looking at the spec, I see that we're not explicit about this anywhere other than in the EventEmitter, see http://docs.ably.io/client-lib-development-guide/features/#RTE6

@paddybyers @SimonWoolf do you think we should be more explicit and add a new spec item that states that any callback provided to the library by a developer must be wrapped so that the exception is always handled and logged to the error logger.  If so, do you think we should also do the following:

* Exceptions relating to the connection callbacks are added to the errorReason and emitted as an error on the connection object
* Exceptions relating to the channel callbacks are added to the errorReason and emitted as an error on the channel object.

**Comment by paddybyers** [comment]
> do you think we should be more explicit and add a new spec item that states that any callback provided to the library by a developer must be wrapped so that the exception is always handled

yes

> and logged to the error logger

yes, with an error message that indicates it's an error in the caller's code, not a library/service error.

> If so, do you think we should also do the following:
> 
> Exceptions relating to the connection callbacks are added to the errorReason and emitted as an error on the connection object
> Exceptions relating to the channel callbacks are added to the errorReason and emitted as an error on the channel object.

No.  We already discussed this. The error events emitted are errors in provision of the service, not errors in user code. We catch errors in user code for defensive purposes only, and log them so that the user knows it happened.

**Comment by mattheworiordan** [comment]
> No. We already discussed this. The error events emitted are errors in provision of the service, not errors in user code. We catch errors in user code for defensive purposes only, and log them so that the user knows it happened.

Yes, you are right, sorry we have covered this. When I reviewed my implementation for my SafeDeferrable and SafeYields to callbacks, what you have said is exactly what we do, see https://github.com/ably/ably-ruby/pull/85

**Comment by mattheworiordan** [comment]
Nothing to do, already done :)
