### ISSUE TITLE
Clarify use of semver on page https://ably.com/documentation/client-lib-development-guide/versioning

### ISSUE THREAD

**Issue by niksilver** [ably/docs#1085]
- **Browser used:** Firefox
- **Device used:** Mac
- **Type of issue:** Content clarification

**Description of issue:**

The content of this page is correct. However, people who read the first (large text) sentence alone, and skip the rest, might think client libraries adhere to semver. The sentence says "Ably aims to follow the semantic versioning scheme..." which is not the same as "Ably follows the semantic versioning scheme...". A couple of suggested alternatives...

* Ably aims to follow the semantic versioning scheme [...]. However, there are differences from the semantic versioning scheme, which are explained below.
* Ably's versioning for its client libraries is derived from the semantic versioning scheme...

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/DOC-314) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
See [internal Slack thread](https://ably-real-time.slack.com/archives/CURL4U2FP/p1620295572143000).
