### ISSUE TITLE
Link not working in the Inband Channel Occupancy Events tutorial

### ISSUE THREAD

**Issue by kavalerov** [ably/docs#1132]
URL: https://ably.com/tutorials/channel-occupancy-events

Link in the first sentence in the last paragraph is not working (`Channel occupancy reveals the number and type of occupants of a particular channel.`)

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/DOC-382) by [Unito](https://www.unito.io)

**Comment by tbedford** [comment]
https://github.com/ably/docs/pull/1133
