### ISSUE TITLE
No link to home/intro section in the table of contents in the Control API docs

### ISSUE THREAD

**Issue by kavalerov** [ably/docs#1150]
<img width="1438" alt="Screenshot 2021-07-27 at 18 52 31" src="https://user-images.githubusercontent.com/1847904/127186794-866a58f5-395d-42e3-92c0-932b9196e148.png">

When I scroll down in the docs, there is no way to go back to this section, and as the links in the top are also hidden after scroll the only way to get to the intro is by scrolling all the way up. More than that, when I am in the middle of the docs, I don't even know that there is this intro section.

┆Issue is synchronized with this [Jira Bug](https://ably.atlassian.net/browse/DOC-436) by [Unito](https://www.unito.io)
┆Attachments: <a href="https://ably.atlassian.net/secure/attachment/11197/image-20210827-162750.png">image-20210827-162750.png</a>

**Comment by kavalerov** [comment]
cc: @ginotoro

**Comment by ginotoro** [comment]
Either we can see if we can add a back to overview/top button or add a new section in the ToC.
