### ISSUE TITLE
Is clientId needed in the transport details

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#117]
See http://docs.ably.io/client-lib-development-guide/features/#RTN2d, states:

> clientId contains the provided clientId option of ClientOptions, unless clientId is null

in the context of the URL used to connect to Ably.  I don't think this adds anything and should be removed in a later version release.

**Comment by paddybyers** [comment]
But a `clientId` can be an attribute of a connection, even if established with basic auth. So how is that communicated to the realtime system without a `clientId` param?

**Comment by mattheworiordan** [comment]
> But a clientId can be an attribute of a connection, even if established with basic auth

But we don't support `clientId` with basic auth in our spec.  See http://docs.ably.io/client-lib-development-guide/features/#RSA4

**Comment by mattheworiordan** [comment]
I am wrong, see http://docs.ably.io/client-lib-development-guide/features/#RTN2d.

@tcard are you not passing the `clientId` as a param to the websocket URL?

**Comment by tcard** [comment]
@mattheworiordan Yes I am: https://github.com/ably/ably-ios/blob/master/Source/ARTWebSocketTransport.m#L137 Why do you think otherwise?

**Comment by mattheworiordan** [comment]
> Why do you think otherwise?

Because you said: 

> The dev does presence.enter, which fails. The connection is not configured for clientId = "foo" (since the token has a wildcard), but she expects presence.enter to implicitly (at the client library level) set the presence message's clientId to foo.

And I assume if `clientId` is a param on the WebSocket URL, then the `presence.enter` should have worked because `clientId` would have been implicit?  I assumed the error `Malformed message; no clientId in message or inferred from connection` came from realtime?  Have I misunderstood?

**Comment by tcard** [comment]
> And I assume if clientId is a param on the WebSocket URL, then the presence.enter should have worked because clientId would have been implicit? I assumed the error Malformed message; no clientId in message or inferred from connection came from realtime? Have I misunderstood?

That's correct. That's why I said the connection is not configured for that client ID. I guess realtime ignores the connection's client ID if you're using token auth?

**Comment by paddybyers** [comment]
> I guess realtime ignores the connection's client ID if you're using token auth?

It doesn't ignore it, and we test that:

https://github.com/ably/realtime/blob/master/test/auth/realtime-auth.js#L128

The exact scenario with presence isn't tested in the various combinations here:

https://github.com/ably/realtime/blob/master/test/realtime/presence.js

so perhaps we need to add a test.

**Comment by mattheworiordan** [comment]
Toni fancy adding a realtime test to see if that is broken or not in the realtime system?

**Comment by tcard** [comment]
OK, I'll add the test.

So what I said at ably/ably-ios#451 is wrong?

**Comment by tcard** [comment]
So, turns out that the iOS lib was using `client_id` instead of `clientId` and realtime was just ignoring it.

After fixing that (https://github.com/ably/ably-ios/commit/0ed5bb98097b12c5f03673556f073580a6720d01) `presence.enter(nil)` works fine and takes the client ID from the connection.

Do we still want to avoid that?

I've added the test to realtime: ably/realtime#569

**Comment by mattheworiordan** [comment]
> After fixing that (ably/ably-ios@0ed5bb9) presence.enter(nil) works fine and takes the client ID from the connection.
> Do we still want to avoid that?

Nope, I thought we had agreed that was now valid given the `clientId` was provided in the ClientOptions and thus implied a `clientId` for the connection?

**Comment by mattheworiordan** [comment]
@tcard any thoughts?

**Comment by tcard** [comment]
@mattheworiordan Not on my part. iOS has been fixed and I've added a test to realtime for the expected behavior.

**Comment by mattheworiordan** [comment]
Ok, closing this issue as `clientId` should be included when known in the transport details and we can confirm it is supported fully in realtime
