### ISSUE TITLE
Feedback on page https://ably.com/documentation/quick-start-guide

### ISSUE THREAD

**Issue by yeboahnanaosei** [ably/docs#1184]
- **Browser used:** Chrome
- **Device used:** Laptop
- **Type of issue:** content incorrect

**Description of issue:** 
Step 1 "Adding the Ably library" on the ["Quickstart guide"](https://ably.com/documentation/quick-start-guide) page shows how to get the Ably Realtime library in a browser.
There is a code snippet that shows a script tag pulling in the library via a cdn url.
The URL in the src attribute is missing the `https` scheme

Script as found on page: `<script src="//cdn.ably.io/lib/ably.min-1.js"></script>`
What is should be: `<script src="https://cdn.ably.io/lib/ably.min-1.js"></script>`

**Reproduction steps:** [The steps required, if any, to reproduce the error]

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/DOC-482) by [Unito](https://www.unito.io)

**Comment by paddybyers** [comment]
@yeboahnanaosei Thanks for the bug report!
