### ISSUE TITLE
Document transportParams, and specifically dormantAfter and heartbeatInterval

### ISSUE THREAD

**Issue by kavalerov** [ably/docs#1245]
For more context please see:
https://app.prodpad.com/feedback/709608/canvas

I couldn't find any place in our documentation where this is documented, and these look like reasonable features for some use-cases.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/DOC-558) by [Unito](https://www.unito.io)

**Comment by kavalerov** [comment]
@paddybyers / @SimonWoolf Just making sure - is there some reason why we haven't documented these before? 

cc: @ben-pickering

**Comment by SimonWoolf** [comment]
It's documented in https://faqs.ably.com/optimising-ably-connections-to-minimize-battery-usage
