### ISSUE TITLE
Node.js server specific recommendations

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#126]
Given **most ** users of the Node.js library will be using it on their servers, we need to either default to making only WS transport available, default to using the WS transport first, or improve our documentation to recommend that the option `transports: ['web_socket']` is used server-side.

Also, our documentation does not make it clear that specifying a `clientId` in `ClientOptions` forces token authentication.  This can come us a big surprise to customers as a result and must be made very clear.

**Comment by mattheworiordan** [comment]
See https://github.com/ably/ably-js/issues/299 for related conversation!

**Comment by paddybyers** [comment]
> default to using the WS transport first

we don't have a way to do this - the various timeouts etc and logic relating to fallback hosts made it too time comsuming to fall back, so we only upgrade. 

Perhaps what we want is an option to specify the preference (just as if the preference had been determined by the library and remembered). Then when the library realises it can't satisfy the preference it re-determines the preference using the usual logic.

**Comment by mattheworiordan** [comment]
> Perhaps what we want is an option to specify the preference (just as if the preference had been determined by the library and remembered). Then when the library realises it can't satisfy the preference it re-determines the preference using the usual logic.

Well perhaps, but if Node is being used on a server that definitely can connect over WS, why even fallback at all?  I don't think adding a preference is necessary, I think we should either default to only use WS in Node, or update the documentation on Node.js to explain that in server environments we recommend WS as a more reliable and better performing transport.

**Comment by mattheworiordan** [comment]
I think we can close this issue as we now record the connection preference for Node.js clients, and if this turns out to be an issue again in future we can reconsider updating the docs to recommend customers force WS if they are confident they don't need other transports
