### ISSUE TITLE
Document fields argument for REST stats API 

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#13]
Stats can be retrieved selectively, this should be documented.

**Comment by paddybyers** [comment]
A `fields` param can be specified on any REST API request which will limit the response body to include only a subset of the fields of the response type.

The format of the `fields` argument is a comma-separated list of field specifiers; each specifier is a field name, or a dot-separated sequence of field names (to specify fields deep within a returned object). For example, to see only the total number of inbound messages in a `stats` query, it is possible to specify:

    GET /stats?fields=intervalId,all.messages,inbound.realtime.messages.count

Where the response body (at any level) is a collection (ie an array), the `fields` request applies to the members of the array.

**Comment by mattheworiordan** [comment]
@paddybyers I was hoping you would add that to the Docs not in an issue!

**Comment by mattheworiordan** [comment]
This is documented
