### ISSUE TITLE
0.9 spec: queryTime tweaks?

### ISSUE THREAD

**Issue by SimonWoolf** [ably/docs#142]
A recent intercom conversation (https://app.intercom.io/a/apps/ua39m1ld/inbox/all/conversations/5539912837), where a generated tokenRequest (created by ably-js in a jsbin) failed due to an out-of-sync clock, reminded me of the queryTime thing, was wondering whether we should discuss it for 0.9.

In the previous discussion [here](https://github.com/ably/ably-js/pull/213#commitcomment-15664406), @paddybyers rejected doing a queryTime by default, but suggested some alternatives. copying here for convenience:

> - query the time if the specific error response from the system indicates a likely clock skew. In general the client should rely on the expiry indication from the server where it can, instead of deciding for itself whether or not the token has expired.

> - if we think the margin for token generation (currently 2 minutes) is too narrow to cover most realistic scenarios then it can be increased;

> - the library can use the `TokenDetails.issued` time to set `serverTimeOffset` if it is successful in getting a token.

> - we could very easily have the realtime system include a reference timestamp in any related error message, which could be used to determined `serverTimeOffset`.

I don't think the first, third, and last of these would really help much, since the lib instance getting the error and/or the tokenDetails (on the client) and the lib instance generating the token request (on the server) generally won't be the same (the server could be trundling along happily having no idea that the token requests it's generating and sending back to clients aren't valid).

AFAICS we could (a) increase timestampExpiry, (b) make `queryTime: true` the default, or (c) do nothing and tell people to keep their bloody clocks in sync :)

**Comment by mattheworiordan** [comment]
I am not against this, but I don't think it's important enough to fit into 0.9 personally.  Most of the time clients generating tokens will be doing this server-side where clocks are very rarely out of sync.  Given no one has reported this as an issue other than in a demo where the usage is contrived, I don't think it's a priority personally

**Comment by mattheworiordan** [comment]
Closed in favour of https://github.com/ably/wiki/issues/130
