### ISSUE TITLE
Update documentation for 0.9 spec

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#153]
See https://github.com/ably/docs/pull/152

Now that we support versioning, we need to update the API docs to include:
- [ ] New details on how connection and channel states are affected, along with presence side-effects
- [x] Reauth details + at least one example of reauth
- [ ] Ensure all docs generally reflect the new strategies employed by the 0.9 spec 
- [ ] Ensure channel attach retry behaviour that moves to suspended is documented

**Comment by SimonWoolf** [comment]
I think this is all done now
