### ISSUE TITLE
rethink msgpack encoding of objects/arrays?

### ISSUE THREAD

**Issue by SimonWoolf** [ably/docs#162]
I know we've got other more important things on right now, but just raising here so we can get back to it at some point.

*(RSL4c3) a JSON Message payload is stringified either as a JSON Object or Array and encoded as MessagePack string type and the encoding attribute is set to “json”*

Isn't that kinda crazy? msgpack's big selling point is it can encode all the structures json can much more efficiently than json does. That's completely lost if we json-encode first.

I realise we mostly use msgpack so we can get efficient binary payloads, but still, seems a shame to throw away all the space gains for objects/arrays, if we're putting them through the msgpack encode/decode process anyway.

(Came across this because I noticed ably-js did this and was sure it must be a bug in ably-js, wrote up an issue then checked the spec and realised it was doing what it was supposed to be doing...)

What was the reasoning behind that spec item?

**Comment by paddybyers** [comment]
We did initially have a `Message` with structured (ie JSON) data being a single deep structure encoded top-to-bottom with msgpack or JSON. However, there are issues with that:

- in strongly typed languages, there is no way for the library to know what customer type to deserialise the `data` into. With the current solution we pass back a type that encapsulates the JSON structure (eg `JSONElement` in Java) which the app can use to map back to his own type. This wasn't possible with the msgpack libraries we looked at - they expected to be able to have the types available to deserialise fully, or they gave you back something partially deserialised which was difficult to deal with, and impossible to deal with portably (ie uniformly irrespective of the transport used)

- we would be doing payload-specific work in the realtime system whenever we process a message - ie fully unpacking the `data`, no matter how complex that structure is;

- the approach would not extend to encrypted payloads - we'd always end up doing the same as we do now.

Encoding a JSON payload into `data` is a client-side convenience only, and separating the `data` structure from the `Message` structure achieves this.

**Comment by mattheworiordan** [comment]
> we would be doing payload-specific work in the realtime system whenever we process a message - ie fully unpacking the data, no matter how complex that structure is;

I think this is the key point.  We have to have interoperability between JSON and MsgPack transports, so we'd now need to inspect the payloads, serialise & deserialise etc.  As a policy, I think we should try and avoid EVER inspecting customer payloads i.e. we're like the mail service, we look at the metadata (address), do some routing and delivery, but we never open that envelope.

**Comment by tcard** [comment]
> we would be doing payload-specific work in the realtime system whenever we process a message - ie fully unpacking the data, no matter how complex that structure is;

This can be avoided though. There are probably more customizable JSON and MsgPack decoders for JavaScript than `JSON.parse` that allow you to specify a destination schema or something like that. E. g. in Go, you can do this:

```
type Message struct {
    Channel string
    Name string
    Data json.RawMessage
}
```

And that `json.RawMessage` tells the JSON decoder to just leave that field as a blob. (Certainly it still needs to be parsed, but that's a really fast op if you don't need the outcome.)

> the approach would not extend to encrypted payloads - we'd always end up doing the same as we do now.

This would complicate the encoding/decoding logic, but we could encrypt the resulting JSON or MsgPack instead of the other way around.

(Anyway, I guess the time in which the amount of work required to do this "right" would pay off in saved bandwidth is still far away.)

**Comment by paddybyers** [comment]
> Certainly it still needs to be parsed, but that's a really fast op if you don't need the outcome

It still takes a length of time that varies with the size of the data.

The primary benefit of msgpack that we care about is that, when the data is opaque, parsing is constant time, so the system doesn't slow down when there are messages that are 10s or even 100s of Kb. We would lose that if the message and data was a single deep structure, even if, after parsing, we treat the data as blobby.

**Comment by SimonWoolf** [comment]
Fair enough. Thanks all for the explanation & discussion!
