### ISSUE TITLE
Presence tutorial

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#176]
@SimonWoolf taking a stab at some ideas for a presence tutorial.

We need a client-side tutorial (Javascript + optionally Ruby EM if you have time) & a client-server example for (Javascript + Node.js, optionally Javascript + Ruby).

See https://www.ably.io/tutorials/publish-subscribe#lang-javascript for a client-side related example.
See https://www.ably.io/tutorials/token-authentication#lang-nodejs for a client-server related example.

For the client-side example perhaps we could show:
- Into - simple explanation of what presence is and how it can be used.
- Step 1 - Set up (this is a generic partial)
- Step 2 - Install Ably (generic)
- Step 3 - Enter channel (let's use a room analogy). Explain that attaching to a channel does not mean you've entered. You need to explicitly enter (avoid any mention of multiple client support, too much info at this stage). We also need to demonstrate at this point that a clientId must be specified. Need to mention explicitly that for this example for simplicity we're assigning a clientId with basic auth, but we don't recommend this in production and should issue a token server-side, with a link to the client-server examples.
- Step 4 - Get current members - explain this is done following the initial sync on the channel
- Step 5 - Subscribe to presence changes - explain that you can subscribe to enter, leave, update events. 
- Live demo - I think we should allow people to enter a room, and change their avatar. So they enter their name, choose an avatar, and enter.  They can then leave at any point, or update their avatar.  Nice to have a raw console + nice graphic of the avatars and people in the virtual room (just a div I expect) will do. See http://www.freepik.com/free-vector/black-and-white-avatars_713015.htm for some possible avatars

For the client-server example perhaps we could show:
- Into - simple explanation of what presence is and how it can be used.
- Step 1 - Set up (this is a generic partial)
- Step 2 - Install Ably on your server (generic)
- Step 3 - Set up your web server
- Step 4 - Enter client (don't worry about auth, again just link to the client-server auth example and explain it's not relevant to this example)
- Step 5 - iFrame with button to get current presence members server-side
- Step 6 - iFrame with button to get presence member history

**Comment by SimonWoolf** [comment]
from slack:

> 21:02 Might be worth only doing the client-side one to keep it simple
> 21:02 The client-server one we can perhaps do in the future
> 21:02 Really not needed now, better to have one example
