### ISSUE TITLE
Check paginatedResult#items

### ISSUE THREAD

**Issue by SimonWoolf** [ably/docs#185]
Current docs seem to have @items@ as both an attribute and a method, for all languages. Spec specifies an attribute. Need to go through languages and see if any actually do have it as a method, and fix documentation accordingly.

**Comment by mattheworiordan** [comment]
Turns out according to the spec @SimonWoolf `isLast` and `hasNext` are methods, see http://docs.ably.io/client-lib-development-guide/features/#TG6.  So the documentation was wrong and misleading.  I am now updating the docs.
