### ISSUE TITLE
Authentication Capabilities Title is cropped

### ISSUE THREAD

**Issue by stmoreau** [ably/docs#1966]
I think there is something odd with `hasTopBar` in `src/components/Article/index.tsx`. The article on this page does have a top bar with only Javascript, but does not have the `pt-64` which causes its title to be a bit cropped.

url: https://ably.com/docs/auth/capabilities

Screenshot of the issue
![image](https://github.com/ably/docs/assets/15115885/7c9323a6-1a72-44ce-824a-757ca9a68d85)

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/EDU-1427) by [Unito](https://www.unito.io)

**Comment by annamariyaivanova** [comment]
This was resolved by https://github.com/ably/docs/pull/1960
