### ISSUE TITLE
Review realtime features

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#20]
@paddybyers and @kouno finally completed the spec for both realtime & REST, see http://docs.ably.io/client-lib-development-guide/features/

Please can you review and fixup any issues you foresee or add your comments here and I will amend. If you notice anything missing please add too.

I will be using this as a check list for all client library developers to confirm what amount of functionality exists and is tested in each client library, so it's important we get this right as it will into a Google Doc with a list to code to prove the feature is implemented.

**Comment by paddybyers** [comment]
I prefer "endpoint" to "end point". Are you ok for me to make that change?

**Comment by mattheworiordan** [comment]
Of course please do

**Comment by mattheworiordan** [comment]
I made the change along with other comments.

I know it's tedious, but can you finish reviewing as this will form the basis of what's needed for all client library developer to deliver their final client library?

**Comment by mattheworiordan** [comment]
@paddybyers can you confirm when you will be able to do this? If you can't do it now, I will communicate this spec out to client lib developers now and tell them a few small changes down the line are likely.  If you can do this soon, I will wait instead.

**Comment by paddybyers** [comment]
https://github.com/ably/docs/pull/21
