### ISSUE TITLE
Make it clearer on docs.ably.io that these aren't the main docs?

### ISSUE THREAD

**Issue by SimonWoolf** [ably/docs#219]
We have some text on the root page, but some people are getting confused between docs.ably.io and ably.io/documentation ([e.g.](https://app.intercom.io/a/apps/ua39m1ld/inbox/all/conversations/7034471644)). We could add a banner or something to the top of every page redirecting people who've stumbled across it to the corresponding page on ably.io/documentation

**Comment by mattheworiordan** [comment]
Yes, great, as mentioned in the Wiki issue, I think a modal that the user has to close the first time they visit would work.

**Comment by mattheworiordan** [comment]
Yes, great, as mentioned in the Wiki issue, I think a modal for a new user that gives them the option of going to the canonical docs or continue would work well.
