### ISSUE TITLE
Spec: ChannelState equal to ChannelEvent

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#225]
Given lines of code like `channel.off(ChannelState.attached, channelStateListener)` in the old docs, I wonder whether we should have actually updated these to `channel.off(ChannelEvent.attached, channelStateListener)` when this could be confusing to users.  `Channel.state` is a `ChannelState` yet to listen for that channel state event, you have to use the equivalent `ChannelEvent`.

Should we instead specify in the spec that `ChannelState.attached == ChannelEvent.attached`?  I have implemented this in Ruby, but not sure this is portable for all languages.  It should be given enums typically have an integer representation.

WDYT @SimonWoolf @paddybyers @tcard?

**Comment by tcard** [comment]
That's not portable for all languages since it's not type-safe. You would be forced to take an int there, and in most cases manually convert from enum to int.

**Comment by paddybyers** [comment]
In Java you can't have one enum type extending another, so we're not going to be able to have a `ChannelEvent` enum. We've opted to have an interface, which is implemented by both `ChannelState` and a new `UpdateEvent` type. So in this case `channel.on(ChannelState.attached, ...)` is correct.

**Comment by mattheworiordan** [comment]
> That's not portable for all languages since it's not type-safe

Well I believe that does depend on the language implementation because some languages, as far as I am aware, simply look at the underlying type which is an int. 

>  So in this case channel.on(ChannelState.attached, ...) is correct.

So how do you listen for `update` then?  Is it `channel.on(UpdateEvent, ...)`?  Looks odd to me :(

**Comment by tcard** [comment]
> Well I believe that does depend on the language implementation because some languages, as far as I am aware, simply look at the underlying type which is an int.

Hmm, right, that can be type-safe as long as the compiler ensures that there's a matching variant in the target enum. But I know of no language that does this (type-safely, ie. ensuring that).

For Swift I think we can do the interface trick that @paddybyers mentions. (In Obj-C enums are pretty much aliases for ints, so passing a variant of a different enum with the same representation would just work.)

If there's any language in which this is impossible I guess we can just not do it, so I'm OK with it.

**Comment by paddybyers** [comment]
> So how do you listen for update then? Is it channel.on(UpdateEvent, ...)?

    channel.on(UpdateEvent.update, ...)

> Looks odd to me :(

Yes, a bit, but then doing what we're doing here is a bit odd. Aside from changing names, I do not believe there is a better way in Java. We looked at multiple options, and implemented a few of them, before deciding this was the least horrible.

**Comment by tcard** [comment]
By the way, @mattheworiordan, given that this would allow the UPDATED to be non-breaking in iOS, would this mean that we should keep the old enum names instead as you initially argued?

**Comment by mattheworiordan** [comment]
>> So how do you listen for update then? Is it channel.on(UpdateEvent, ...)?

> channel.on(UpdateEvent.update, ...)

Wow, that is pretty horrible.  If that is the only option, why not simply go with `channel.on(ChannelEvent.[attached|update|...]` over `channel.on(ChannelEvent.[attaching|attached|...] | UpdateEvent.event)`.  The syntax of the latter just looks terrible IMHO -  `UpdateEvent.event` is odd, surely this should just be `ChannelEvent.update` so that it allows for other channel events in future.

>> Looks odd to me :(

> Yes, a bit, but then doing what we're doing here is a bit odd. Aside from changing names, I do not believe there is a better way in Java.

Well why not only emit `ChannelEvent.*` for `on*, off` handlers?  At least then the user knows what to expect.  Using an interface means we're moving into Java land where there are unnecessary abstractions from what we are trying to achieve.  I know this issue is all about not using `ChannelEvent.*`, but given what we've come up with, that's a whole lot better.

My view on we should approach this is as follows, in order of what is supported by the language:

* `on(event)` where event is a symbol or string, is the simplest in that the user can simply do `on(:attached)` or `on('updated')` without caring if it's a channel event or state, given that value will match with `channel.state`.  In these languages we should raise an exception if `event` in `on(event)` is incompatible (in Ruby this happens now).  The downside to this approach is not typing or intellisense.

* In statically typed languages where Enums are comparable by value, we could support `on(ChannelState.attached)` as well as `on(ChannelEvent.attached)` given that `channel.state == ChannelState.attached == ChannelEvent.attached`.  When this is actually possible, developers will see from intellisense that the definition is `on(event: ChannelEvent)`, yet they can equally just use a channel state without caring about this.  I would argue this is the best of the lot when available.

* In statically typed languages where Enums are not comparable by value, we should only allow a `ChannelEvent` to be passed in.  Whilst we could use an interface and support `ChannelState` and `UpdateEvent`, this is going to confused users and intellisense will be near on useless i.e. it will present an empty abstract interface instead of a dropdown with possible event values.

WDYT?

> By the way, @mattheworiordan, given that this would allow the UPDATED addition to be non-breaking in iOS, would this mean that we should keep the old enum names instead as you initially argued?

I think the iOS lib will have to abide by option 2 or 3 above, probably 3 given what I understand you are saying.

**Comment by tcard** [comment]
> In statically typed languages where Enums are comparable by value, we could support on(ChannelState.attached) as well as on(ChannelEvent.attached)

Those languages are basically C (which includes Objective-C). In C/Obj-C the compiler will emit a warning if you pass enum A where it asks for enum B an there's nothing we can do about it. Now, if I understand what you're proposing, ie. having the `ChannelEvent` enum with a single variant `UPDATED`, then you're proposing that every time they listen for state changes they get a compiler warning?

<img width="835" alt="captura de pantalla 2016-12-16 a les 14 11 29" src="https://cloud.githubusercontent.com/assets/727422/21263885/9635e0fe-c399-11e6-9096-53ef3d04a28f.png">

I mean, I understand that this is your original proposal opening this issue, but I know of no languages that let you really implement this.

> In statically typed languages where Enums are not comparable by value, we should only allow a ChannelEvent to be passed in. Whilst we could use an interface and support ChannelState and UpdateEvent, this is going to confused users and intellisense will be near on useless i.e. it will present an empty abstract interface instead of a dropdown with possible event values.

I agree. If we have an interface, honestly I think it should just be a temporary thing for avoid breaking code from 0.8 to 0.9, but we still should have two separate `ChannelState` and `ChannelEvent` enums. It's probably unnecessarily convoluted otherwise.

So in the end I think it's OK to just have two separate enums, `ChannelState` and `ChannelEvent`, and copypaste all cases from `ChannelState` to `ChannelEvent`, and then only be able to listen to `ChannelEvent`.

Addressing your original point: I don't think this distinction is confusing at all. It's maybe confusing to _us_ because we're used to the old case, but having the type of the channel state be different to the type of the events emitted by a channel is completely reasonable in my book (some would say Best Practice™ indeed, even when the only possible event was a state change!).

Aside: if we ever have a library in a language with a proper type system with sum types (like Swift, Rust, Haskell, Elm, etc.), all this goes away as you could do this:

```swift
enum ChannelState {
    Attached
    // ... all states ...
}

enum ChannelEvent {
    StateChange(ChannelState)
    Updated
}

channel.on(StateChange(Attached), ...)
channel.on(Updated, ...) 
```

**Comment by mattheworiordan** [comment]
@paddybyers I would like to decide on what to take from this issue tomorrow if possible as I believe this has an impact on Java which we're hoping to finish up soon?

**Comment by paddybyers** [comment]
I'm ok in principle to have a `ChannelEvent` enum that contains all states as well as `update`. I really don't like the idea that it breaks everyone's existing code. Do we also add overloaded `on()` methods so existing code continues to compile?

**Comment by mattheworiordan** [comment]
Closing this as we agreed that:

* We would add an `event` attribute to the state change objects
* Where possible, we may overload the event emitter methods to support `on(ChannelState)` for example, but we'll issue a deprecation warning.

See https://github.com/ably/docs/pull/217 for recent commits
