### ISSUE TITLE
RTL7c review 

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#226]
RTL7c states "Implicitly attaches the Channel if the channel is in the INITIALIZED state. However, if the channel is in or enters the DETACHED or FAILED state before the operation succeeds, it will result in the listener not being registered and an error being indicated, typically to the optional callback where the language permits"

The more I thought about this, the more I dislike this.

You can register a listener on a channel when it is ATTACHING, ATTACHED, SUSPENDED, DETACHED or FAILED, however if it's INITIALIZED and the attach fails for some reason, you can't.  Yet after it fails, you can attach a listener and that is fine.

This does not make sense to me.

I understand the rationale and why we implemented it, it was primarily because we wanted users to know when an implicit operation failed.  If we want to do that, we should expose that result in a callback / promise / deferrable / whatever, or not at all if necessary.  But this rule is very confusing and will lead to bugs for developers who have already hit snags of registering listeners multiple times.

I propose the listener is always registered as the channel state has nothing to do with that operation, and if a customer wants to know the result of the implicit operation, we expose that to them in an additional callback etc.

**Comment by tcard** [comment]
> I propose the listener is always registered as the channel state has nothing to do with that operation

That sounds good to me.

> if a customer wants to know the result of the implicit operation, we expose that to them in an additional callback

That's exactly what we do in iOS. We have two methods, `subscribe(callback: (Message) ->)` and `subscribe(withAttachCallback: (ErrorInfo) ->, callback: (Message) ->)`.

**Comment by paddybyers** [comment]
Agreed.

**Comment by SimonWoolf** [comment]
:+1:

**Comment by mattheworiordan** [comment]
Should I squeeze this into 0.9 given it's a minor change, or leave for 0.10?  Votes?

**Comment by paddybyers** [comment]
0.9 because it makes sense, and I don't want any barriers to then move to 0.10 :)
