### ISSUE TITLE
Document reactor routingKey interpolation

### ISSUE THREAD

**Issue by SimonWoolf** [ably/docs#227]
initial quick draft:

routingKeys (which are used as the partitionKey in kinesis) are arbitrary interpolable strings. Interpolation is done using #{...}, similar to ruby.

The contents of the interpolation is a variable. Currently supported: "channelName", "message.name", and "message.clientId".

This is optionally followed by a filter. Filters use a pipe syntax, similar to AngularJS filter expressions, jq, or bash. Currently supported filters are "hash" and "moduloHash". "hash" transforms the variable into a stringified 32-bit fingerprint, and takes an optional numerical argument, the base to use when stringifying (defaults to 16). "moduloHash" does the same, but runs the result through a modulo function before stringifying -- useful for bucketing. It takes one mandatory argument (the number of buckets) and one optional (the base).

If using a filter, you can specify a tuple oftwo or more variables as the input to the filter. It should be comma-separated and delimited with parentheses.

Examples:

"just-the-channel-name-#{channelName}"
"hashed channel name: #{channelName | hash} as hex, #{channelName | hash(10) as decimal}"
"channel name mod 256: #{channelName | moduloHash(256)}, or in octal: #{channelName | moduloHash(256, 8)}"
"message name: #{message.name}, clientId: #{message.clientId}"
"hexadecimal hash combining all message properties: #{(message.name, message.clientId, channelName) | hash}"

**Comment by paddybyers** [comment]
> arbitrary utf8 ... strings

They're strings. utf-8 is an encoding.

**Comment by SimonWoolf** [comment]
OK. "unicode strings"?

(wanted to convey that it wasn't limited to ASCII -- hey, someone might want to get into the spirit of the season and go for a routing key of `"🎄 ❄️ 🎄 ❄️ 🎁🎁🎁 #{channelName} 🎁🎁🎁 ❄️ 🎄 ❄️ 🎄"`)

**Comment by paddybyers** [comment]
> "unicode strings"?

This is 2016. I think "strings" says it :)

**Comment by tcard** [comment]
> This is 2016. I think "strings" says it :)

If only that may be so. I'm called "CÃ¡rdenas" by machines almost more often than "Cárdenas"...

**Comment by paddybyers** [comment]
> If only that may be so. I'm called "CÃ¡rdenas" by machines almost more often than "Cárdenas"...

Sad but true I'm sure. Blame Windows.

It's ironic that Windows has had multi-byte encoding support before nearly anything else - I know the man who first implemented support for Japanese in Windows in 1979 with Bill Gates (he worked for the inappropriately-named "ASCII Corporation of Japan"). But by API design and choice of default encoding unicode is still treated as a second-class citizen.

**Comment by SimonWoolf** [comment]
Documented in https://support.ably.io/solution/articles/3000081103-what-is-the-format-of-the-routingkey-for-an-amqp-or-kinesis-reactor-rule-
