### ISSUE TITLE
Realtime Connection review

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#23]
@paddybyers, @kouno and @SimonWoolf, would you mind reviewing the latest update I have made to the "Realtime Connection documentation":http://docs.ably.io/realtime/connection/ with commit https://github.com/ably/docs/commit/deee337b015f1efa0a011c0d3f3115bc36bd1db0.  Note this is published to http://docs.ably.io/realtime/connection/, and the Types page is at http://docs.ably.io/realtime/types/

There have been various other fixes and tweaks to the docs repo, however I think this commit is the only one relevant to review.

**Comment by mattheworiordan** [comment]
Note I have published this page to the main website at https://www.ably.io/documentation/realtime/connection, however there are lots of formatting bugs, I have raised an issue for that, https://github.com/ably/website/issues/265

**Comment by SimonWoolf** [comment]
:+1:

**Comment by mattheworiordan** [comment]
@SimonWoolf I've addressed your feedback in https://github.com/ably/docs/commit/155702ad88f9f64caf71113b576edfe9020b2a4a, thanks.

**Comment by paddybyers** [comment]
I've not reviewed it yet.
