### ISSUE TITLE
Show a warning when using `token` or `tokenDetails` in ClientOptions

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#232]
I can't think of any reason, other than for testing, why a user would use only a `token` or `tokenDetails` in ClientOptions.

Whilst we should support it, should we consider showing a warning when it is used with a link to a support article explaining why we don't recommend this approach?

**Comment by paddybyers** [comment]
In the Rest case, where the library is being used statelessly, I expect it would be quite common.

**Comment by tcard** [comment]
I can think of one: to avoid additional requests on page load (such as Ably's auth request) you get the token server-side and send it as initial state for your client side alongside your code itself. This kind of setup is getting increasingly common I think.

**Comment by mattheworiordan** [comment]
> In the Rest case, where the library is being used statelessly, I expect it would be quite common.

Really, so the user would provide an explicit token and then catch the exception, then reissue the token and try again.  Why wouldn't the just use `authCallback`?

> I can think of one: to avoid additional requests on page load (such as Ably's auth request) you get the token server-side and send it as initial state for your client side alongside your code itself. This kind of setup is getting increasingly common I think.

Yes, but I said "why a user would use **only** a token or tokenDetails...".  So if they provide a means to renew, then of course we don't show the warning.

**Comment by mattheworiordan** [comment]
If we display a warning, it should follow a standard error format and thus allow the user to find a solution in our help docs. See https://github.com/ably/wiki/issues/142 for more details.  We should agree this now perhaps and add to the spec for all client library issued errors.

**Comment by mattheworiordan** [comment]
Closing in favour of #300
