### ISSUE TITLE
Default capabilities

### ISSUE THREAD

**Issue by SimonWoolf** [ably/docs#245]
`(RSA6) The capability for new tokens is JSON stringified (REST API default is allow all {"*":["*"]}, see TK2b)`

`(TK2b) capability string – Capability requirements JSON stringified for the token. When omitted, the REST API default to allow all operations is applied by Ably, with the string value {"*":["*"]}`

It's easy to misinterpret that as meaning the client library should set the capabilities string to `{"*":["*"]}` by default when requesting a token. That's how the ably-ios lib interprets it - https://github.com/ably/ably-ios/issues/576

Trouble is, that then breaks everything if someone has a key restricted to a subset of resources, see https://github.com/ably/realtime/issues/780

We should first decide if we want to change the realtime behaviour (https://github.com/ably/realtime/issues/780), and then if we don't, then we should clarify RSA6 (and further document how capabilities intersection works).

**Comment by mattheworiordan** [comment]
I don't think that request is wrong personally, see https://github.com/ably/realtime/issues/780

**Comment by paddybyers** [comment]
The default should always be to specify nothing, and realtime will respond with what you've got, and that will still be true even if we decide to do something re #780

**Comment by mattheworiordan** [comment]
> The default should always be to specify nothing, and realtime will respond with what you've got, and that will still be true even if we decide to do something re #780

That's not what I meant.  It's irrelevant whether the default should be `nil`, the point is that if someone requests a `*` capability and the API key has a subset, it should return the intersection.  Regardless of whether the default a client then uses is `nil` or `*`, if a customer asks for `*` which is reasonable to expect, we should intersect capabilities.
