### ISSUE TITLE
Remove ambiguity from spec in terms of attribute return values

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#248]
See https://github.com/ably/ably-java/pull/277#issuecomment-272860644 for context

**Comment by tcard** [comment]
There's no real "formal" difference between a function that takes no arguments returning (non-IO) `T` and a field of type `T`. In some languages (Ruby, ML-like languages) there's no difference at all, and in many others you can do computed attributes (Swift, Python, ES6, ...). So I don't see the point on specifying one over the other. We can just say that those can be implemented either way, depending on the needs of the platform or whatever.

**Comment by mattheworiordan** [comment]
@tcard I would agree, and hence why I thought the IDL was sufficient.  But I would agree that in the languages where there is a difference, I don't see any harm being explicit to avoid that ambiguity to avoid inconsistent implementations like we saw in https://github.com/ably/ably-java/pull/277#issuecomment-272860644.  WDYT?
