### ISSUE TITLE
Add error docs for both Realtime & REST docs

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#252]
See https://github.com/ably/wiki/issues/175

We should detail what types of errors people can expect and how to handle them

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/EDU-76) by [Unito](https://www.unito.io)

**Comment by Srushtika** [comment]
@mattheworiordan now that we have URLs leading up to support articles explaining the error the user has hit and possible ways to solve that, is this issue still relevant or good to be closed?
