### ISSUE TITLE
Angular version of ToDo needed

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#26]
@kouno can you please create an Angular version of either the Backbone.js or Ember.js examples at http://docs.ably.io/code-index/.  The examples are in https://github.com/ably/docs/tree/source/content/code/website-examples.

Once done, please can you incorporate into the website, see https://github.com/ably/website/commit/7a59aca3e05241097306275d3b1a7226d390aca4 for an example.

**Comment by kouno** [comment]
@mattheworiordan You can close this now :)
