### ISSUE TITLE
Java issues with doc for 1.0

### ISSUE THREAD

**Issue by psolstice** [ably/docs#264]
1. realtime/authentication:

`authorize()` uses different order of arguments in 0.9: `TokenParams`, then `AuthOptions`

2. realtime/connection:

in one of the code snippets
```realtime.connection.on('connected', new ConnectionStateListener() {```
replace 'connected' with `ConnectionEvent.connected`. A text preceding this snippet must also be changed according to `ConnectionState`/`ConnectionEvent` scheme of emitting events

3. realtime/channel-messages:

In the code snippet regarding encryption this line
```options.cipher = params;```
is wrong (`cipher` is of wrong type and private). It should be changed to either
```options.encrypted = true; options.cipherParams = params;```
or to `ChannelOptions.fromCipherKey` method of `ChannelOption` creation

In "Handling channel errors" section. First sentence. synchronous -> asynchronous

4. realtime/encryption:

The doc mentions the key should be 128 or 256 bit long. In the implementation 192 is a valid value too. Also for Java 128 bit is default (IMHO because of additional actions required to enable 256-bit crypto in Oracle JRE).

Crypto.getDefaultParam`: we decided against function with such arguments
the code snippet is wrong (same mistake as the one mentioned above in section (3) of this issue)

generateRandomKey: definitely not a Java syntax, code snippet uses `withCipher` instead of `fromCipherKey`

io.ably.lib.types.ClientOptions: should read `io.ably.types.ChannelOptions`, only `CipherParams` are supported, `withCipherKey` -> `fromCipherKey`

io.ably.lib.util.Crypto.CipherParams: default key length for Java is 128, `PKCS#7` -> `PKCS#5`

Some of the issues mentioned above happen in REST sections as well

**Comment by mattheworiordan** [comment]
Thanks @psolstice.
