### ISSUE TITLE
Consider tweaking httpMaxRetryDuration and httpRequestTimeout

### ISSUE THREAD

**Issue by SimonWoolf** [ably/docs#274]
Currently `httpMaxRetryDuration` is 10s, which is less than `httpRequestTimeout`. That means that if a library takes [TO3l6](https://docs.ably.io/client-lib-development-guide/features/#TO3l6) at its word, it contradicts [RSC15d](https://docs.ably.io/client-lib-development-guide/features/#RSC15d): the latter requires a fallback host attempt on http timeout, but that's barred if `httpMaxRetryDuration < httpRequestTimeout`.

(ably-js currently avoids this by not taking `httpMaxRetryDuration` seriously, but we should decide on a proper solution for 1.0/1.1/whatever. See previous discussion re ably-js [here](https://github.com/ably/ably-js/pull/147#issuecomment-148421193))

**Comment by mattheworiordan** [comment]
Given the insignificance of this change, I think we should fix it now.  

Perhaps just as simple as 12s for an HTTP request and max retry duration of 15s?

**Comment by SimonWoolf** [comment]
Sounds ok to me (or maybe 10s http / 15s mrd, or 12s http / 18s mrd, to give the second request a little more breathing room). @paddybyers might have an opinion on this re good interactions between clientside timeouts and realtime timeouts (see prev discussion on those [here](https://github.com/ably/wiki/issues/112))?

**Comment by paddybyers** [comment]
I tend to agree that 12/15 doesn't give enough headroom for subsequent requests.

I'm not sure there's really much difference between 10/15 or 12/18; probably 10/15 is best. I don't think we get many requests succeeding in the 10-12s window.
