### ISSUE TITLE
Possible tweak to retry strategy for requestToken

### ISSUE THREAD

**Issue by SimonWoolf** [ably/docs#286]
Two separate customers ([1](https://app.intercom.io/a/apps/ua39m1ld/inbox/all/conversations/8794158606), [2](https://app.intercom.io/a/apps/ua39m1ld/inbox/search/conversations/8785197734?q=nonce)) have reported getting "Nonce value replayed" errors, at times when we've been having server issues. Presumably, this is from clients which get a signed token request, do a requestToken call with it which times out (but actually succeeds at some point after the client has given up), then try it again at a different data center.

Should we edit the spec to say that if a client lib has to retry a requestToken call using a token request due to a timeout, it should re-get a new token request from the auth server?

**Comment by paddybyers** [comment]
> Should we edit the spec to say that if a client lib has to retry a requestToken call using a token request due to a timeout, it should re-get a new token request from the auth server?

Yes, or perhaps only on receipt of that specific error code.

**Comment by mattheworiordan** [comment]
> Yes, or perhaps only on receipt of that specific error code.

But there won't be an error code if it times out surely?

> Should we edit the spec to say that if a client lib has to retry a requestToken call using a token request due to a timeout, it should re-get a new token request from the auth server?

Yes, makes sense to me

**Comment by paddybyers** [comment]
> But there won't be an error code if it times out surely?

I mean if the same tokenRequest is retried, and results in that error code, then go and get a new one

**Comment by SimonWoolf** [comment]
> I mean if the same tokenRequest is retried, and results in that error code, then go and get a new one

Sure. on second thoughts that's probs better than my original suggestion, since then the retry logic is in the requestToken callback, rather than cluttering up the generic http request retry functionality with token-specific logic
