### ISSUE TITLE
Token auth tutorial wrongly allows 'javascript' language selection

### ISSUE THREAD

**Issue by SimonWoolf** [ably/docs#288]
https://www.ably.io/tutorials/token-authentication#lang-javascript . Tutorial is broken if you select it.

(Also, the language bar in this tutorial functions as a strange mix of client-side and server-side language choices. E.g. 'java' gives you java+javascript, 'android' gives you nodejs+android, 'swift' gives you ruby+swift, 'ruby' gives you ruby+javascript, etc. We might want to consider if there's a more user-friendly way of presenting that, though the way we separate website (inc language bar) from tutorial content makes that a bit tricky at the moment)

**Comment by mattheworiordan** [comment]
> Tutorial is broken if you select it.

I'm not sure what you mean here @SimonWoolf?  Select what?

**Comment by mattheworiordan** [comment]
Ah, I can see now, you mean select Javascript.
