### ISSUE TITLE
REST API documentation needs to be updated to reflect changes in 0.7.x branch

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#3]
I think this is one for you.  @kouno and I will tackle the client lib API docs.

**Comment by mattheworiordan** [comment]
@paddybyers we also need to have a page that explains how the limits work for our clients so that they understand any restrictions that may exist that they should be aware of.

**Comment by paddybyers** [comment]
Sure, there is some material we can start with in the old wiki.

**Comment by mattheworiordan** [comment]
This is done
