### ISSUE TITLE
Warning when using a token without a means to renew

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#300]
Given how many people will be caught out when using the library with a token string, should we not always log a warning when someone uses a realtime library with a token without a means to renew the token?

We could create a unique error (warning) code and include a link to a suitable article, see https://github.com/ably/wiki/issues/142.

WDYT?

**Comment by SimonWoolf** [comment]
:+1: good idea

**Comment by mattheworiordan** [comment]
@SimonWoolf as far as you are aware, if a `token` and (`authUrl` or `authCallback`) are provided, the client libs should use the `token` first, and once expired, use `auth*` right?  I think that is not happening in all libraries (see tickets/1986). I don't think we've been explicit anywhere in our spec about what should happen in that situation right?

**Comment by SimonWoolf** [comment]
> I don't think we've been explicit anywhere in our spec about what should happen in that situation right?

Funny you should ask, I have an open docs PR clarifying this exact thing :)
https://github.com/ably/docs/pull/186/files#diff-11900b395df266bc2bbfc1d11bdfc7a0R163

**Comment by mattheworiordan** [comment]
> I have an open docs PR clarifying this exact thing :)

Wow, that was a long time ago!  Glad to see we're going over old ground!

**Comment by mattheworiordan** [comment]
We should probably generate an error code for this, and emit a warning in all client libs with this error code now that [we support error help](https://github.com/ably/docs/pull/293)

**Comment by SimonWoolf** [comment]
Fixed by https://github.com/ably/docs/pull/412
