### ISSUE TITLE
Should `useTokenAuth: false` force basic auth?

### ISSUE THREAD

**Issue by SimonWoolf** [ably/docs#312]
Noticed an inconsistency between ably-java and ably-js just now.

RSA4 requires that: `Token Auth is used if useTokenAuth is set to true, or if useTokenAuth is unspecified and any one of the following conditions are met: a clientId is specified; authUrl or authCallback is provided; an explicit token or TokenDetails is provided `

Ably-java takes advantage of the fact that the condition is an `if`, not an `if and only if`, and continues to use token auth if `useTokenAuth` is `false` as long as one of the other conditions is true. Wheras ably-js [disables token auth if `useTokenAuth` is `false`](https://github.com/ably/ably-js/blob/master/common/lib/client/auth.js#L57). (The distinction is mostly only relevant if the user specifies a `clientId`, which would otherwise force token auth). We should standardise on one behaviour and clarify the spec accordingly.

FWIW I'd prefer we standardise on the ably-js behaviour -- if someone specifies `useTokenAuth: false`, they presumably have a good reason for wanting basic auth, so why should we stop them? (Not to mention it would have been useful for https://support.ably.io/helpdesk/tickets/2248 , we could just have told the customer to specify `useTokenAuth: false` to solve the problem)

cc @mattheworiordan @paddybyers

**Comment by paddybyers** [comment]
One issue here is that in java you can't have `useTokenAuth == undefined`. So there is a default value in `ClientOptions` which (I assume) happens to be false. There is no way to indicate that the user chose a non-default value. If we want the behaviour to be that specifying a `clientId` by default triggers token auth, then we have to keep the java behaviour, at least for java.

**Comment by SimonWoolf** [comment]
So e.g. see https://support.ably.io/helpdesk/tickets/2526 for a usecase. Customer is doing REST publishes, with a different clientId each time (as it's on behalf of different clients). Before every publish it gets a token, for itself, which it then uses exactly once.

This is needlessly high-latency for the customer, and needlessly resource-intensive for us.

> If we want the behaviour to be that specifying a clientId by default triggers token auth

If we're happy to drop that behaviour, then sure, that'd be a good and easy solution. (I don't see the justification for it anyway - what behaviour are we protecting against by forcing someone who has an api key and voluntarily wants to publish with a client id to do it with a token?)

**Comment by SimonWoolf** [comment]
@mattheworiordan any opinion?

**Comment by paddybyers** [comment]
I agree if someone has a key there's no point in making them create a token

**Comment by mattheworiordan** [comment]
> I agree if someone has a key there's no point in making them create a token

I agree too.  I can't help feeling there was a reason we opted for automatic token auth when assuming a `clientId`, but I cannot remember what that was now :(  I'll stew on it.
