### ISSUE TITLE
Channels and Messages documentation is quite verbose and should be split

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#313]
As the channel state documentation has grown, the [channels and messages](https://www.ably.io/documentation/realtime/channels-messages) documentation has become quite verbose.  I think there is an argument now to separate this out into two separate distinct pages.

**Comment by mattheworiordan** [comment]
@tomczoink @Srushtika this issue already existed in docs.

**Comment by Srushtika** [comment]
This is all done now. Hence, closing the issue.
