### ISSUE TITLE
Common API methods

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#315]
The docs can be overwhelming to new users because the API docs are quite vast.  Increasingly we need to allow people to get up and running with docs more quickly by providing high level info at the start, with references to key methods they need to be aware of, and then let them dive deeper later into the details and API references.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/DOC-89) by [Unito](https://www.unito.io/learn-more)

**Comment by tbedford** [comment]
We have the Ably Deep Dive on the roadmap for Q3-21. This follows on from the Quickstart and leads people deeper into Ably. That should help a lot with this.
