### ISSUE TITLE
Should POSTing a new device registration be idempotent?

### ISSUE THREAD

**Issue by tcard** [ably/docs#327]
(Extracted from a more general discussion at https://github.com/ably/realtime/pull/993.)

Right now, you can't [POST a device registration](https://docs.ably.io/rest-api/#post-device-registration) that is already registered. @mattheworiordan proposes instead than a POST for an already existing device just succeeds, as long as the fields remain the same; the already existing would be returned (maybe with a reissued `updateToken`?).

The use case would be that, on a POST that succeeds on the server but fails to be acknowledged to the client, the client may reissue the POST, and things would just work instead of having to deal with the "failed because it was already created" case.

Part of https://github.com/ably/wiki/issues/161.

**Comment by tcard** [comment]
A possible argument against this is that it's a security flaw, unless we decide the device ID constitutes a client secret. If a client knows another device's ID (and its other, non-secret fields), it may pass for it by issuing a POST request with this ID and the rest of the fields, and it will get the device's secret update token.

Of course, if we say that knowing another client's device ID is a security breach by itself, then this is fine. It is coherent with GET /push/deviceRegistrations requiring admin privileges; also, you can subscribe a device to a push channel just by knowing its device ID. But then, what do we need the update token for? Why isn't a single secret key per device enough?

**Comment by tcard** [comment]
( @mattheworiordan I opened this here without giving it much thought, but maybe ably/wiki is a better place for it.)

**Comment by paddybyers** [comment]
Closing; device creation is now idempotent
