### ISSUE TITLE
Move Push.publish -> PushAdmin.publish 

### ISSUE THREAD

**Issue by tcard** [ably/docs#328]
See https://github.com/ably/realtime/issues/1037.

Needs to be done in iOS, Java, JS.

**Comment by mattheworiordan** [comment]
This is a breaking change for a 1.1 release, and also needs to be included in Ruby

**Comment by tcard** [comment]
@mattheworiordan I thought this was done in Ruby already. You linked to https://github.com/ably/ably-ruby/commit/ee8a66a6988fd2507a7376ce088961e85245891a .

**Comment by funkyboy** [comment]
- This is done in [iOS](https://github.com/ably/ably-ios/pull/642).
- Not done in JS, AFAICT (https://github.com/ably/ably-js/pull/395, https://github.com/ably/ably-js/pull/435)
- Doesn't look like it's done in Java (I looked at [this PR](https://github.com/ably/ably-java/pull/308/files))

**Comment by mattheworiordan** [comment]
@funkyboy can you raise issues in each repo to address this?  Then close this issue perhaps?

**Comment by funkyboy** [comment]
Opened [JS related issue](https://github.com/ably/ably-js/issues/497)
