### ISSUE TITLE
Assume Role ARN help

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#336]
@SimonWoolf we need to have a support article that explains how Assume Role works for AWS Reactor rules, why it is used (to remove the need to share credentials), and how users can go about using the Assume Role functionality (i.e. we need to confirm the IAM user / role they need to add).

Can you do that please in the support site, unless you think it should go somewhere better?

**Comment by SimonWoolf** [comment]
Fixed by https://support.ably.io/solution/articles/3000071908-authentication-for-reactor-rules-for-aws-reactor-events-for-lambda-functions-reactor-firehose-for-k
