### ISSUE TITLE
3 separate REST-vs-realtime lib solutions pages

### ISSUE THREAD

**Issue by SimonWoolf** [ably/docs#347]
I've been adding information (presence considerations, publish patterns, etc) to https://support.ably.io/support/solutions/articles/3000060319-should-i-use-the-rest-or-realtime-library- . Just noticed there's now also https://support.ably.io/support/solutions/articles/3000069281-when-should-i-use-the-rest-client-library-vs-the-realtime-client-library- and https://support.ably.io/support/solutions/articles/3000069280-when-should-i-use-the-realtime-library-vs-the-rest-library- . We should consolidate into one.

**Comment by SimonWoolf** [comment]
Also, none of the three currently address the need to use realtime clients for high publish volumes (esp now we have transient publishes), given hourly api request limits etc. e.g. https://support.ably.io/helpdesk/tickets/2666

**Comment by mattheworiordan** [comment]
There was some reasoning to this some time back, but I can't recall.  I think there may have been links from the main API docs to these solution pages, so in some instances we wanted specific content to address that question, whilst others were more generic.  But I agree this is now unnecessary.  Saying that, if we consolidate, we must avoid making this one behemoth of page that is so verbose and unwieldy that it becomes unapproachable for devs.

I think high publish volumes and [transient publishes](https://github.com/ably/docs/issues/357) should not yet go into our documentation, but perhaps in our solution pages for now.  Transient publishes is part of a later spec release so not officially supported.

**Comment by SimonWoolf** [comment]
The quick start guide links to https://support.ably.io/solution/articles/3000060319-should-i-use-the-rest-or-realtime-library- ; couldn't find any docs that linked to the other two at a quick grep. So I consolidated everything into that article, moved it to General/FAQs, and deleted the other two.
