### ISSUE TITLE
Raise an exception when publishing presence messages when queueMessages is false

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#35]
In the same way that `Channel#publish` throws an exception when publishing in a channel or connection state that is not acceptable (depending on the `queueMessages` client option), see RTN6c2 and RTN6c3 of http://docs.ably.io/client-lib-development-guide/features/, I propose we add the same expectation for all `Presence` events that publish messages such as `enter`, `enterClient`, `update`, `leave` etc.

@paddybyers thoughts?

**Comment by paddybyers** [comment]
> I propose we add the same expectation for all Presence events that publish messages such as enter, enterClient, update, leave etc.

Agreed.

**Comment by mattheworiordan** [comment]
Closed with https://github.com/ably/docs/commit/ac1c1fa013ab9c278ce648356ea6831fe3a5ded9
