### ISSUE TITLE
Hourly limits (e.g. API request limits) are underdocumented

### ISSUE THREAD

**Issue by SimonWoolf** [ably/docs#364]
No information in either https://support.ably.io/support/solutions/articles/3000053845-do-you-have-any-connection-message-or-rate-limits-on-accounts- or the account dashboard on the hourly api request limit, or how it's calculated. (How _is_ it calculated, for that matter? Tried grepping the website repo, but can't find what sets it. People do run into it, e.g. if doing high publish volumes with REST clients, https://support.ably.io/helpdesk/tickets/2666)

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/DOC-100) by [Unito](https://www.unito.io)

**Comment by SimonWoolf** [comment]
cf https://github.com/ably/website/issues/1327

**Comment by mattheworiordan** [comment]
This is in fact addressed in https://github.com/ably/website/issues/1307.  I'll leave this open though as this is a documentation issue so complimentary to the functionality needed for customers to see all limits and be alerted to them.
