### ISSUE TITLE
Clear documentation for using authURL vs authCallback needed for web/non-web clients.

### ISSUE THREAD

**Issue by Srushtika** [ably/docs#367]
authURL might be using web specific features such a cookies, etc thus making it recommended to be used in web environments. But this is not the case with non-web environments, where authCallback is more recommended.

We need to have documentation that discusses this, so users can have a clear idea about which one to use.

**Comment by funkyboy** [comment]
An effective solution would be to remove authURL authentication from the SDK :)

**Comment by Srushtika** [comment]
Addressed in https://github.com/ably/docs/pull/561/commits/61b335fedfc5c516634dc3863a63446ebce0ef27
