### ISSUE TITLE
Quickstart .NET instructions out of date

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#379]
From a customer in regards to the [Quick Start Guide](https://www.ably.io/documentation/quick-start-guide).  Code at https://github.com/ably/docs/blob/master/content/root/quick-start-guide.textile

> so far found 2 problem. 
> 1. install system.net.http also
> 2. No class named Channel exists, instead it is giving IRealtimeChannel

@withakay could you please take a look?

**Comment by foyzulkarim** [comment]
![image](https://user-images.githubusercontent.com/497812/36309341-6e58e332-134e-11e8-85a1-a7bb1f88ee65.png)

**Comment by withakay** [comment]
Regarding point 1. `System.Net.Http` should be installed as a dependency of the ably nugget package, so I will have to investigate why that is not happening. I have added an issue [here](https://github.com/ably/ably-dotnet/issues/180) so this can be investigated.

For point 2, In the quick start I would suggest we just `var` for example; 
`var channel = ably.Channels.Get("quickstart");`

I have made a PR for this here https://github.com/ably/docs/pull/380

**Comment by mattheworiordan** [comment]
Thanks, I will close this issue then as this issue is handled elsewhere now.

**Comment by foyzulkarim** [comment]
regarding point 1. the required version of system.net.http ably is requesting is 4.1.1.1 but the dependency installed the version 4.0.0.0
thus when i do the compile, it gives me build error. to solve this, i had to install the system.net.http separately. i guess your packaging needs to be updated too. thanks. 👍

**Comment by withakay** [comment]
@foyzulkarim can you confirm the platform you are using (.Net Framework on Windows, Xamarin etc etc.). Thanks!

**Comment by foyzulkarim** [comment]
.NET Framework. 4.6.2 (Windows Forms Application)
