### ISSUE TITLE
Can't copy code from snippet

### ISSUE THREAD

**Issue by funkyboy** [ably/docs#392]
Steps:

- visit https://www.ably.io/documentation/quick-start-guide 
- pick Java at the top
- try copying the two lines
```
import io.ably.lib.types.*;
import io.ably.lib.realtime.*;
```
- start dragging from the first line, the move the mouse down to select also the second one
- the second one does not get selected, so you can copy only the first.

I tried with both Safari and Chrome on macOS. If I reload the page (sometimes a few times) it works as expected.

PS. Just venturing a hypothesis: _maybe_ some of the popups "steal" focus (or events) from the "select text" procedure.

**Comment by tornato7** [comment]
Hey just wanted to support that this issue should be fixed. It'd be nice to be able to copy code from tutorials. Here's an example of a code snippet that can't be copied:
https://i.imgur.com/5jUFZNw.png

**Comment by mattheworiordan** [comment]
@tornato7 sorry for the inconvenience. I know this is being worked on btw.  We should have a fix out soon as it only affects some browsers.

**Comment by Srushtika** [comment]
This issue is fixed now. Hence, closing the issue.
