### ISSUE TITLE
Need a support page for how to change the name of accounts

### ISSUE THREAD

**Issue by tomczoink** [ably/docs#394]
Need to make a support article explaining that to change the name of an account, you need to go to 'account settings'.

**Comment by mattheworiordan** [comment]
It probably would have taken around the same time to create a support article as creating this issue 😁

**Comment by mattheworiordan** [comment]
P.S. Please label issues.

**Comment by tomczoink** [comment]
Added at https://support.ably.io/solution/articles/3000079791-how-do-i-change-my-account-s-name-or-email.
