### ISSUE TITLE
Auth docs refactor and JWT

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#395]
As discussed last week, when we add the JWT documentation, we should consider a refactor of the auth documentation in general.

Notes from the meeting:

Auth home page (overview of authentication, which one to use and when etc). Then break down details for each auth type:

* Basic Auth
* Token Auth
* JWT

REST & Realtime Auth pages:

* More lightweight in terms of explanations
* Simple explanation of which auth to use - simple table, with links to find out more
* Then get straight into an example for each

**Comment by Srushtika** [comment]
@tomczoink can this be closed?

**Comment by tomczoink** [comment]
@Srushtika besides a table all have been applied, we'd have to decide if we want to polish the auth pages further or not.
