### ISSUE TITLE
Documentation navigation restructure

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#398]
@tomczoink @Srushtika here is a summary of what we agreed in terms of nav restructure.  Note that nav restructure will require a separate set of changes in the docs repo as well as the website as the navs are not shared.

This will require us to produce some new content:

* A generic pub/sub page
* A generic presence page
* A generic history page
* A [best practice guide](https://github.com/ably/docs/issues/396)

![image](https://user-images.githubusercontent.com/43789/37273611-a3ac5584-25da-11e8-8b2d-e0a47dc19eb6.png)

**Comment by Srushtika** [comment]
TODO: Update Core features>Authentication with Core features> Security and Auth

**Comment by Srushtika** [comment]
Asana project link: https://app.asana.com/0/632022997116386/632022997116386

**Comment by Srushtika** [comment]
This is now live on the website.
