### ISSUE TITLE
Max total publish rate into reactor queues

### ISSUE THREAD

**Issue by SimonWoolf** [ably/docs#403]
[Customer](https://app.intercom.io/a/apps/ua39m1ld/inbox/inbox/conversation/15281989258) asked about this just now.

https://support.ably.io/support/solutions/articles/3000053845-do-you-have-any-connection-message-or-rate-limits-on-accounts- currently lists: "Max messages published into the queues from all pub/sub channels per second | 100 | 200". We don't currently implement any such limit. Should we make an issue to implement it (once we have cluster-wide rate limits)?

If so, what should it be? 200/s seems quite low given that that's the limit we have for Webhooks, and we want to use limits to encourage people with high message rates to move away from webhooks towards queues or streams. Is the worry about the load on the rabbit boxes, so we want to enourage people with rates higher than that to set up their own queues somewhere?

@paddybyers @mattheworiordan

**Comment by mattheworiordan** [comment]
> Max messages published into the queues from all pub/sub channels per second | 100 | 200". We don't currently implement any such limit. Should we make an issue to implement it (once we have cluster-wide rate limits)?

Well we are supposed to.  Bugger, why did we not pick this up before when we made other API changes? 👎 

> If so, what should it be? 200/s seems quite low given that that's the limit we have for Webhooks, and we want to use limits to encourage people with high message rates to move away from webhooks towards queues or streams.  Is the worry about the load on the rabbit boxes, so we want to enourage people with rates higher than that to set up their own queues somewhere?

How are Webhook limits enforced, I don't see that defined anywhere either in the standard limits object?

Well the reason this exists is partly that we want to keep the load on our queue clusters low, but also so that [people have triggers to get in touch with us to upgrade to Ent](https://github.com/ably/wiki/issues/277).

**Comment by SimonWoolf** [comment]
I'll make a realtime issue to implement it once we have the infrastructure in place to do so (i.e. account-wide instantaneous rate limits).

> How are Webhook limits enforced, I don't see that defined anywhere either in the standard limits object?

Looks like it's hardcoded. It's also not exactly a rate limit, just a max number of messages per webhook post, which since there can only be one in-flight post at a time, ends up being effectively a rate limit (albeit preferring the newest messages) with value dependent on how fast the receiving server responds.

It's currently 1000, which is what's documented in https://www.ably.io/documentation/general/webhooks#transport . Not sure where the 200 in the limits article came from. I'll edit the article to match reality for that -- not sure if we want to consider lowering it to 200? (probably still using the current postMaxCount method rather than a rate limit in case anyone's now relying on the semantics of that, if not the exact count)
