### ISSUE TITLE
MQTT documentation

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#405]
Before we launch MQTT officially, we need to update the documentation to include details on how to use MQTT.  This issue is here to start a conversation on what should be implemented before launch.

cc @SimonWoolf @tomczoink @Srushtika @atanasovd

**Comment by mattheworiordan** [comment]
I recommend:

* Add a new section under Realtime / REST which is MQTT
* List our MQTT client libs for download in the website (mostly done at https://github.com/ably/website/pull/1396)
* Show a few examples of how to use MQTT pub/sub in a few select languages. We don't need to be exhaustive and certainly don't need to think about consistency as there is no consistency in SDKs 
* Have a sub-page on authentication and how that works with MQTT and Ably
* Have a page on how MQTT features map to Ably
* Shortcomings page
* Link to MQTT tutorials

I realise a lot of this could sit in solutions, but the solutions section is really more about FAQs & quick help.

**Comment by Srushtika** [comment]
@tomczoink Just came across this issue, is this good to be closed?
