### ISSUE TITLE
Spec behaviour messages published before a resumed connection

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#41]
@paddybyers please see https://github.com/ably/ably-ruby/commit/23877d594b7c8325fad4bcf4e0baadff49796aac#diff-5a92463d6ab8ad3fc8cf8aff5cfde6f8R573

I have implemented a new feature in the Ruby library following a discussion with Peter a few days ago as follows:
- Connection is opened 
- Message is published over the transport
- The transport is disconnected
- The connection is resumed with a new transport
- The message ACK has not yet been received because the transport was disconnected beforehand, so the client library resends the message and gets an ACK

I would like your view on whether this is the correct behaviour.  The alternative is to fail the message that was sent, but that does not feel right given it was actually sent successfully.

**Comment by paddybyers** [comment]
The second copy of the message should get an `ACK` because that signifies that it has been received and processed successfully. The realtime system should notice the duplicate and not perform any further processing.

**Comment by mattheworiordan** [comment]
This is covered in the 0.9 spec
