### ISSUE TITLE
Add JWT to the spec

### ISSUE THREAD

**Issue by funkyboy** [ably/docs#416]

**Comment by paddybyers** [comment]
The requirement is that client libraries are able to be initialised (or re-authorised) with a JWT string, in all  places where they can accept an Ably token string. This includes:

- in the library constructor (`new Ably.Rest(<token>)`);
- in `ClientOptions` (new Ably.Rest({token: <token>})`);
- as a successful return from an `authCallback` or `authURL`.

In all cases the library handles the token opaquely, so no new functionality is required. However, `RSC1` requires libraries, if they support overloaded constructors, to determine whether a single string argument to the constructor is an API key or a token. We now need to specify how this is determined, and ensure that the library does not mis-identify a JWT as an API key.

A test needs to exist that verifies that the library correctly identifies a JWT as a token, can be initialised with that, and can successfully authenticate to Ably. This should be a real JWT, generated using a library appropriate to the test environment.

**Comment by paddybyers** [comment]
Also, we need a document on the site that defines what profile of JWT we do support; the base information is in https://docs.google.com/document/d/17i68ctOlnijeqOwrOyvZiAmHHzxos99rTYFhQiWNuC8/edit

**Comment by mattheworiordan** [comment]
@paddybyers @funkyboy I would recommend we make this change before adding tests in other libraries otherwise we're just going to end up doing more work.

I would add to the notes from @paddybyers above that we additionally need to make sure clients can renew tokens correctly automatically, so perhaps expiring with REST, and then expiring with Realtime using the Auth protocol message to renew.

**Comment by mattheworiordan** [comment]
P.S. When reviewing, please see my very quick comments on what I think needs to be addressed in https://github.com/ably/ably-ruby/pull/137.

**Comment by paddybyers** [comment]
See https://github.com/ably/docs/pull/420

**Comment by mattheworiordan** [comment]
Closing as reolved in #420
