### ISSUE TITLE
Add .editorconfig to all repos

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#427]
Given we are seeing contributions from 3rd parties who don't know what our style guides are, I would like us to add `.editorconfig` files to all repos, and also consider tools like `rubocop` where feasible in all repos. 

See http://editorconfig.org/ for details on editor config

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/DOC-107) by [Unito](https://www.unito.io/learn-more)

**Comment by tbedford** [comment]
Editor config file is present in docs repo.
