### ISSUE TITLE
connectionStateTtl default is 60s, should be 120s

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#433]
See https://docs.ably.io/client-lib-development-guide/features/#DF1a

Shouldn't this be 2 minutes?

**Comment by paddybyers** [comment]
That's the default used by realtime, so yes I think it should change as the library default. When libs respect what realtime says then it doesn't really matter what they use as their default, but we should still make it consistent.

**Comment by SimonWoolf** [comment]
Fixed in master-1-1: d4782d7cd0fc2da277cd86ba4ab52c4797b364be
