### ISSUE TITLE
Push IDL types are missing

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#450]
See https://github.com/ably/docs/blob/13faf2ef123848cb843cbedbce900b2039ed0924/content/client-lib-development-guide/versions/features-1-0__1-1.diff#L686-L688

This is the "final" 1.1 spec yet is incomplete.  We need to fix this before we can legitimately consider the 1.1 spec finalized.

**Comment by mattheworiordan** [comment]
@paddybyers I thought this had been resolved, but it appears this is still missing.  Please can confirm if this needs to be filled out or not, and when it will be done?

**Comment by tomczoink** [comment]
@paddybyers @mattheworiordan this is done now I believe?

**Comment by paddybyers** [comment]
yes
