### ISSUE TITLE
Add details to the "Why some publishes are slow"

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#459]
See https://docs.google.com/document/d/1LIoz5YcfwMFPcd9iCcanHgQYxZQRiFN8zydz7pgqz9o/edit#heading=h.yiouyjl51uvj (this document is not a public document as it references a customer, do not make public mistakenly)

We need to:

* Remove any reference to the customer
* Add mention of upcoming idempotent publishing support over REST
* Link to this from the why some publishes are slow support article
* Add this article to our solution articles

**Comment by tomczoink** [comment]
Done in https://support.ably.io/solution/articles/3000067435-why-are-some-rest-publishes-on-a-channel-slow-and-then-typically-faster-on-subsequent-publishes-.
