### ISSUE TITLE
"Live Demo" in pub/sub tutorial doesn't work

### ISSUE THREAD

**Issue by tomczoink** [ably/docs#476]
In the Live Demo for pub/sub tutorial, you're supposed to be able to open two different pages in your browser and have them use the same channel. This does not appear to be the case. This was tested in Chrome.

In addition, it mentions the possibility of scanning a QR code instead, but there is no QR code. We either need to add one or remove mention of it.

<img width="761" alt="screen shot 2018-08-01 at 09 23 19" src="https://user-images.githubusercontent.com/9784119/43510391-65812494-956d-11e8-9e2f-0ec7567d77c9.png">

**Comment by Srushtika** [comment]
Works fine for me on both Chrome and Safari:

<img width="772" alt="screen shot 2018-10-05 at 10 54 42" src="https://user-images.githubusercontent.com/5900152/46528995-26b2dc00-c88d-11e8-867f-e8a77753dc1c.png">

Can you check once again, please?

**Comment by tomczoink** [comment]
Seems to work for me now as well, hopefully was just an issue with the site at the time then.
