### ISSUE TITLE
Adding minimize throughout the docs

### ISSUE THREAD

**Issue by tomczoink** [ably/docs#487]
We need to look into adding minimize functionality throughout the docs where suitable.

Suitable examples are tables or sections which provide additional information, consecutive example sections, and useful for large sections which need reducing in size.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/DOC-111) by [Unito](https://www.unito.io/learn-more)

**Comment by tbedford** [comment]
We are going to remove minimize feature unless there is a strong case for keeping it, as customers miss important information.
