### ISSUE TITLE
Stats results: unit / intervalGranularity / intervalTime confusion everywhere

### ISSUE THREAD

**Issue by SimonWoolf** [ably/docs#492]
Following on from https://github.com/ably/docs/pull/491 ("add unit; correct granularity explanation") -- our client libraries are a bit of a mess with this.

Some (e.g. [ably-ruby](https://github.com/ably/ably-ruby/blob/2b35c6f89b75acb7a7a02a77fb0ed42552445c30/lib/ably/models/stats.rb#L186), [ably-ios](https://github.com/ably/ably-ios/blob/76056922296439e2a7fb7e90b07c2396a900354c/Source/ARTStats.m#L213)) have `intervalGranularity` methods that calculate the unit from the length of the `intervalId`, which will give the wrong answer for day and month stats, see https://github.com/ably/docs/pull/491 .

Others (e.g. [ably-dotnet](https://github.com/ably/ably-dotnet/blob/e76f6c94df952171a38bc84a2f5cfd1ac1a42e6f/src/IO.Ably.Shared/Statistics.cs#L21), [ably-php](https://github.com/ably/ably-php/blob/de6aa54c154459bc21d64a4e2e1cb20f32acbddd/src/Models/Stats.php#L40)), perhaps mislead by the [features spec IDL](https://docs.ably.io/client-lib-development-guide/features/), assume the returned json contain an "intervalGranularity" property (they don't, it's "unit"), similarly `intervalTime`.

The stats object returned by realtime contains a `unit`. Why would we want to rename the field to `intervalGranularity` clientside, what's wrong with `unit` (which has the advantage that it's the same property name as the corresponding field in the stats query)?

@mattheworiordan @paddybyers @funkyboy

**Comment by paddybyers** [comment]
There was a discussion related to this some time back: https://github.com/ably/realtime/issues/531

Quickly the complexity got out of hand, and so nothing happened.

Personally I think having `unit` and `intervalId` as currently used by realtime can be documented quite clearly and is a lot better than an alternative that doesn't exist because we didn't have time to implement it. Alternatives can be considered when we do API 2.0.

**Comment by mattheworiordan** [comment]
Ok, separate `unit` and `intervalId` it is.  However, `unit` is not an attribute of the stats object at present.

**Comment by SimonWoolf** [comment]
fixed by https://github.com/ably/docs/pull/491
