### ISSUE TITLE
Push notification documentation 

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#501]
* [x] https://www.ably.io/documentation/general/smart-notifications
  * Stop referring to this as Smart Notifications, it's Push Notifications.
  * Use our landing page format potentially, so it's more of a marketing content dev starting page?
  * We can add a section about Smart Notifications being worked on, see https://blog.ably.io/smart-notifications-the-next-evolution-of-messaging-6dcb24bf857, and move the section at the top further down.
  * Make it clear mobile push notifications are stable (Android & iOS)
  * Add a nice diagram to the Push Notifications home page.  We can go "off brand" to get something in place without design support and rebrand later.
  * Features need to be listed out more clearly.
  * Make it clear web push notifications are in beta.  Get in touch if you want to get early access
  * List out tutorials for Android & iOS, and docuemntation.
* [x] Realtime Push Notifications home page https://www.ably.io/documentation/realtime/push
  * Add diagrams to channel-broadcasting & direct publishing sections
  * Remove beta notice.
  * Link to download should take users to the normal download page, remove custom push download page.  Need to consider how we address the matrix of which SDKs support push or not though.
  * Add links to tutorials
* [x] Explain clearly that there are two ways to activate device, directly with Ably from the device, or via your app servers. We need to add details on both (and links to tutorials), and include pros and cons for each. See https://www.ably.io/documentation/realtime/push/activate-subscribe
* [x] All API docs are missing from from the activation section https://www.ably.io/documentation/realtime/push/activate-subscribe.  Need to make sure all our Realtime Push APIs are documented, see related gap at https://github.com/ably/docs/issues/450
* [x] Review all subsections for accuracy - check with SDK devs if all documentation is accurate, fields are correct, method definitions correct etc.
* [x] Update REST push documentation as above https://www.ably.io/documentation/rest/push
* [x] As push is now 1.1, we need to add 1.1 support to the entire docs repo, and all libraries that support push should now be on 1.1 and released.
* [x] Merge in 1.1 docs PRs, and create a new diffs 1.0 -> 1.1 diff (see https://github.com/ably/docs/pull/449, and https://github.com/ably/docs/pull/401) 
* [x] Document the missing IDL section: https://github.com/ably/docs/issues/450
* [x] Add a troubleshooting push notification section (or support article)
  * Direct push publish with sample code they can use to test
  * Using the dev console to monitor live errors

### Client libs

The goal is to have all libraries that support push be released with a 1.1 tag.

As we are now heading towards a situation where client libraries may be released under a version number but not have full support, we need to address https://github.com/ably/docs/issues/482.  We should also resolve https://github.com/ably/docs/issues/382 at the same time.

  * Javascript: push needs to be merged in https://github.com/ably/ably-js/pull/395, but I believe for our browser version, we should have a new variant now which includes the push code.  Later, that could also include the push activation code.  We need to a 1.1 release.
  * Javascript: web notifications (https://github.com/ably/ably-js/pull/435/) - can we not rebase the work that Tony did, fix any major inconsistencies with the new activation changes, and release a beta version that people can test at least?
  * Ruby: merge push work and release 1.1
  * Python: merge push work and release 1.1
  * PHP: push work to be done still, and then released 1.1
  * Android: complete 1.1 and release
  * Go: Nothing to do, although we may try and add push support.
  * .NET: wait until 1.0 release is stable, then look at push support

**Comment by Srushtika** [comment]
Did the changes @tomczoink yet to review and merge.
Documentation changes: https://github.com/ably/docs/pull/563
Website changes: https://github.com/ably/website/pull/1935

**Comment by Srushtika** [comment]
Docs improvements to be done, based on feedback from the freelance tutorial writer:

[ ] - Improve documentation for `push-admin` and `push-subscribe` permissions enabling

**Comment by tomczoink** [comment]
@Srushtika stuff to be done to my knowledge:

Realtime Push Notifications home page https://www.ably.io/documentation/general/push
* Add a nice diagram to the Push Notifications home page.  We can go "off brand" to get something in place without design support and rebrand later.
* Add diagrams to channel-broadcasting & direct publishing sections
* Add links to tutorials


General:
* Review all subsections for accuracy - check with SDK devs if all documentation is accurate, fields are correct, method definitions correct etc.


Add a troubleshooting push notification section (or support article)
* Direct push publish with sample code they can use to test
* Using the dev console to monitor live errors

**Comment by Srushtika** [comment]
> include pros and cons for each. See https://www.ably.io/documentation/realtime/push/activate-subscribe
@paddybyers/ @SimonWoolf  any ideas on this?

**Comment by mattheworiordan** [comment]
@tomczoink @Srushtika what's the status on this issue?

**Comment by Srushtika** [comment]
@mattheworiordan since this was one of the few push related issues, all of the tasks here were added into a [single list in Asana](https://app.asana.com/0/803498094368727/list). These are all done now. The docs need some updates though as per the recent issues you raised elsewhere. This issue, however, is good to be closed.
