### ISSUE TITLE
Doc / demo API key comments

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#508]
In our docs and demos, we often include temporary API keys as a convenience for developers.  This is great, however it can also lead to some confusion as they don't necessarily know that the API key is temporary, and is not the one they should be using.

We could of course use the API keys from their own accounts, but that's confusing too and potentially dangerous:

* Will they be aware the key used is secret and not mistakenly share their code?
* Hwo we do know which API key they want to use from which app, or even which account?

As such, we think it would be better to simply now add a comment to all code examples where API keys are added automatically stating that developers should insert their own API keys.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/DOC-112) by [Unito](https://www.unito.io/learn-more)

**Comment by tbedford** [comment]
This is quite old, we now clearly have a warning in each code snippet, plus a drop down to select specific API key/secret when logged in.
