### ISSUE TITLE
Update limits documentation

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#514]
See https://support.ably.io/solution/articles/3000053845-do-you-have-any-connection-message-rate-or-other-limits-on-accounts-

It's missing some of our newer limits like api request per hour, per second limits.

We should also document channel and connection maxCreationRate limits.

I noticed this whilst creating https://support.ably.io/solution/articles/3000082364-explanation-all-metrics-within-rate-limit-errors

**Comment by tomczoink** [comment]
Updated with max creation limits + api limits.
