### ISSUE TITLE
Queue setup docs and tutorials are outdated

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#516]
Some time back we unified Reactor Rules so that queue rules along with any other type of rule are managed from the Reactor tab.

A customer has reported that we didn't update our documentation, sadly :(

Specifically he mentioned the following:

* [x] Section 2.2 of "https://www.ably.io/documentation/general/queues" mentions "bottom of the queues tab within your app dashboard"
* [x] "https://support.ably.io/support/solutions/articles/3000062196-how-can-i-set-up-a-queue-rule-" - see item 2, "Click on the Queues tab and click "Create a new Queue rule"
* [x] "https://www.ably.io/tutorials/queue-amqp-wolfram-alpha" - under step 5, see text "Follow these steps to set up a new queue rule"

We need to also:

* [x] Check all other docs, support articles & tutorials to make sure we've not got outdated docs

**Comment by tomczoink** [comment]
@mattheworiordan all of this should be done now, anything you know of that I've missed or good to close?

**Comment by mattheworiordan** [comment]
That's superb, thanks @tomczoink.  Mind notifying the customer we've updated the docs, he'll be impressed by your haste!
