### ISSUE TITLE
Best practice for presence

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#522]
@Srushtika whilst talking to a customer today, I remember we have two other common gotchas that we should include in our [best practice guide](https://www.ably.io/documentation/best-practice-guide).

* [x] Remember that a single clientId can be present one or more times on a channel. Therefore, if you are subscribing to leave events, don't assume that `clientId` is gone, as they could be present more than once before that. Check the presence set using `get`
* [x] We have a lot of code to handle the complexities of keeping the members present on a channel in sync in our realtime client lib.  So don't try and build your own code to keep track of who is present or not a channel by subscribing to enter/leave events, and instead rely on our `get` method on the realtime lib, that is always in sync and kept up to date.

**Comment by Srushtika** [comment]
Added these in [here](https://github.com/ably/docs/pull/524)
