### ISSUE TITLE
Best practice when you've received limit notifications

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#523]
When customers receive an email about exceeding a quota, nearing a limit, or exceeding a limit, we could do a better job at helping customers to work out a plan.

I think we need a very helpful "guide" article that walk users through:

* Understanding what the email & limits mean
* Why limits are needed
* How to calculate usage i.e. messages, max per hour, max per second, simple models to do this.  How to consider API requests / Token requests etc.
* Burstable capacity, and how we can boost this for Biz & Ent customers
* Viewing your detailed stats
* Viewing any notifications / breaches of limits or quotas on your account

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/DOC-114) by [Unito](https://www.unito.io)

**Comment by paddybyers** [comment]
Per-namespace stats might be important. Customers seem to have difficulty working out which channels are the culprit.

**Comment by mattheworiordan** [comment]
> Per-namespace stats might be important. Customers seem to have difficulty working out which channels are the culprit.

Sure, but that's a new feature as opposed to best practice guide no?

**Comment by paddybyers** [comment]
> that's a new feature as opposed to best practice guide no?

yes
