### ISSUE TITLE
Feedback on page https://www.ably.io/tutorials/web-rtc-introduction, typos

### ISSUE THREAD

**Issue by saulimus** [ably/docs#527]
- **Browser used:** whatever
- **Device used:** whatever
- **Type of issue:** graphical

**Description of issue:**
The image app/assets/images/tutorials/webrtc-with-ably.png on top of the tutorial page says "singnalling" beside the arrows.

**Reproduction steps:**
Read carefully. :)

**Comment by tomczoink** [comment]
This has now been fixed with dba5ec3fca4c2cda7d6cfccf5ec13d235392d9a1, thanks for bringing it to our attention.
