### ISSUE TITLE
Update any documentation or support articles on why channels take a while to make

### ISSUE THREAD

**Issue by tomczoink** [ably/docs#538]
We should update all relevant articles and documentation to include the depth of the below text regarding channel creation times and REST speeds.

> The main thing to bear in mind is that Ably channels are optimised for sending messages with very low latency once active. They are not (currently) optimised for speed of setup: instantiating a channel that was not previously active anywhere involves a handshake between (typically) three AWS regions globally, which takes a couple of seconds. (Instantiating a channel in a region that it was not previously active in also has a significant amount of latency, but not nearly as much).
> 
> The reason we made that tradeoff is that, if there are any actual subscribers to that channel, then that price will already have been paid at the time the subscriber attaches: by definition a channel that someone is already attached to is active. So it's a cost that for most usecases is paid only when it doesn't matter -- i.e. when the channel has no subscribers. (It can't be optimised away entirely due to history and channel rules).
> 
> (The other thing is that REST publishes are a little slower than realtime publishes for other reasons. E.g. making an TLS connection involves a 3-way handshake; we default to https. When a connection pool is used that cost won't need to be paid for every REST publish; but there are a few other costs that do, that are frontloaded for realtime connections (e.g. making a connection from the frontend that the REST request hits to the channelmaster in that region if one isn't there already).)
> 
> Just to give an idea, here's some operations ordered from lowest to highest latency:
> - a realtime publish to an already-attached channel
> - a REST publish to a channel that was aready active (e.g. had subscribers or another recent publish) in the publish region
> - a REST publish to a channel that was aready active in some other region
> - a REST publish to a channel that was not previously active anywhere
>
> So depending on your needs, some possible solutions are to publish using a realtime client and attach to any channels you know you're going to publish to before publishing to them (see the [Publish patterns](http://support.ably.io/support/solutions/articles/3000060319-should-i-use-the-rest-or-realtime-library) article for discussion on the upsides and downsides to this); or to have some test subscribers, so the channels are already active when you publish to them.
>
>It is also possible to use a parameter for REST publishes that will give a 'quick ack': that is, if the channel is not currently active, we will respond to the REST request once we have authenticated it, rather than what we normally do which is wait for the channel to confirm that it has delivered it. This should reduce the amount of time it takes for a publish to a previously-nonexistent channel to be acked from ~2s to ~20ms (plus roundtrip and tls connection creation time). Note that with that enabled, technically this means it is possible for our delivery guarantee to be violated: for example, if a channel is active in region X but is exceeding its 50/s rate limit, then with this option, a publish in region Y would return success even though the message will actually be rejected for breaching the per-channel rate limit. So we don't generally recommend it except for lower QoS usecases. But let me know if you're interested in that.

**Comment by mattheworiordan** [comment]
@tomczoink can we close this?
