### ISSUE TITLE
For spec 1.2 consider better solution of Google Sheets

### ISSUE THREAD

**Issue by tomczoink** [ably/docs#565]
Currently it's hard to maintain, and this will become a larger issue in the future. This is notably bad for adding new users/items.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/DOC-117) by [Unito](https://www.unito.io)

**Comment by mattheworiordan** [comment]
The sheet has been drastically improved now.  When we come to support 1.2, we should definitely also consider:

* Introducing two new states: needs review (when a spec item has been updated in that spec release i.e. from 1.1 to 1.2) and not applicable (for say push on a library that does not support push target)
* Automate a task to update the needs review status for any item flagged as 1.1 / 1.2 etc.

**Comment by QuintinWillison** [comment]
We have planned an SDK Team initiative to work on solving this (without using Google Sheets!) in our near-term roadmap. I'm closing this issue as while @tomczoink is correct in his opening comment (problems persist in this area), we've recently had less focus on the tracking spreadsheet as we know there are ways this can be done better. FYI, @AndyNicks
