### ISSUE TITLE
Nanoc upgrade + performance

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#574]
Nanoc is now painfully slow as any changes require the entire site to be rebuilt.  We should upgrade to Nanoc 4, and then look at performance as we need to be able to work more quickly locally.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/DOC-120) by [Unito](https://www.unito.io/learn-more)

**Comment by mattheworiordan** [comment]
Hey @tomczoink, did you make any progress with this by any chance?

**Comment by tomczoink** [comment]
A PR for Nanoc upgrade is up now at #599 @mattheworiordan .

**Comment by mattheworiordan** [comment]
@tomczoink can we close this, or is some of this still outstanding?
