### ISSUE TITLE
Best practice: Realtime vs REST and token auth

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#591]
We continue to see two behaviours with customers that we should work on resolving:

* In spite of us having documentation that explains the difference between tokens and token requests, customers continue to request tokens server-side. We see this very frequently in support tickets.
* Customers use a Realtime client library server-side when all they need is a REST library.  This problem is even worse when we discover they are using the library to simply request a token, or within a Lambda function.

Possible ideas to help customers resolve these common issues:

* Detect when a user has issued more than X tokens on their account, and send a helpful message about knowing when to use tokens or token requests
* Detect when an account has become "active" and send an email explaining when to use REST libs vs Realtime libs.

We could also go further by:

* Detecting when a realtime lib is instance quickly and then disposed quickly, and show a warning.
* Detect when a realtime lib is only used for publishing and show a warning.

My concern with these last two points is that we'll almost inevitably end up showing false-positive warnings.  We could of course detect this pattern of behaviour server-side somehow, and generate an email from that.  That feels like a lot of work and could be complicated.

Finally we could of course review our docs and figure out how we can make this problem clearer.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/DOC-121) by [Unito](https://www.unito.io)

**Comment by tbedford** [comment]
Addressing only the documentation aspects of the above, on the issue of Realtime vs REST we do document that:

* https://ably.com/documentation/realtime#realtime-vs-rest
* https://ably.com/documentation/rest#rest-vs-realtime
* https://knowledge.ably.com/should-i-use-the-rest-or-realtime-library

We should also have something on it in the Getting Started guide though too. I will look into that.

On the question of auth tokens versus token requests, I don't think we say anywhere that servers shouldn't use token auth, so we should probably recommend they use Basic Auth explicitly, with key secured on the server using .env file or other suitable approach.

On all of the above, I think we should make things clearer at suitable points in the docs, and especially in the Best Practice Guide.

**Comment by lmars** [comment]
> On the question of auth tokens versus token requests, I don't think we say anywhere that servers shouldn't use token auth, so we should probably recommend they use Basic Auth explicitly

Yes, I would suggest simply changing the "Basic Authentication" and "Token Authentication" sections on [this page](https://ably.com/documentation/core-features/authentication) to be titled something like "Server-Side Authentication" and "Client-Side Authentication" respectively, since you should really only be using keys server-side, and tokens client-side.
