### ISSUE TITLE
Python REST docs force to version 0.8

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#605]
We support 1.0 for Python, yet the docs force 0.8 for some reason.

Can we check that this issue does not exist for other languages too Realtime & REST?

![screenshot 2019-01-26 at 14 17 58](https://user-images.githubusercontent.com/43789/51788368-36746a00-2175-11e9-8840-01592b1b8bf6.png)

**Comment by tomczoink** [comment]
Should all get fixed with my 1.1 changes, for example in https://github.com/ably/docs/pull/583/files#diff-80469b1c5e0dd2e8ff3da0c178748ae7L9.
