### ISSUE TITLE
Document how to test and implement AssumeRole with Reactor

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#614]
We should add tips on how to get this to work, and any tools we can offer to help them test this.

Can we have a separate solution article for this, and then link to this article from Reactor rule docs / support articles?

We should make sure we have a Reactor solution article for each Reactor type too.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/EDU-136) by [Unito](https://www.unito.io)

**Comment by SimonWoolf** [comment]
(for reference, what we have at the moment, which Matt's saying is insufficient, is https://support.ably.com/en/support/solutions/articles/3000071908-authentication-for-reactor-rules-for-aws-reactor-events-for-lambda-functions-reactor-firehose-for-aws-sqs-and-kinesis- )
