### ISSUE TITLE
json code blocks are being hidden on docs

### ISSUE THREAD

**Issue by Srushtika** [ably/docs#624]
<img width="344" alt="screenshot 2019-02-19 at 12 02 45" src="https://user-images.githubusercontent.com/5900152/53013706-5595ad00-343e-11e9-8957-d340532859d4.png">

See above, the code blocks recognized by 'json' are enabling 'display-none' by default and they contain a single CSS class '.with-lang-nav', something seems to be happening in that class that needs investigating.

┆Issue is synchronized with this [Jira Bug](https://ably.atlassian.net/browse/DOC-142) by [Unito](https://www.unito.io/learn-more)

**Comment by mattheworiordan** [comment]
@Srushtika please tag

**Comment by tomczoink** [comment]
Hey @Srushtika could you clarify on where this is happening? The pages with JSON I've found seem to be working fine for me and displaying properly.

**Comment by tbedford** [comment]
Closing as does not appear to be an issue. Please let me know if otherwise.
