### ISSUE TITLE
Update Reactor docs in regards to the new test rule feature

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#625]
https://github.com/ably/website/pull/2131 adds support for a test rule button on rules.

We should check the solution articles that exist for debugging, testing and setting up rules, along with our documentation for Reactor more generally to make sure this is mentioned.

**Comment by tomczoink** [comment]
Updated support articles https://support.ably.io/a/solutions/articles/3000074193 and https://support.ably.io/a/solutions/articles/3000062287
