### ISSUE TITLE
Publish with a single Message object

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#644]
I've noticed in the push documentation, we are using an undocumented form of the publish method.

Here's the docs on the method with overloaded versions:

<img width="768" alt="Capto_Capture 2019-03-23_12-19-08_pm" src="https://user-images.githubusercontent.com/43789/54865950-e0cbd080-4d65-11e9-9467-59613dc344da.png">

Yet here is what is being called from the push publishing docs:

<img width="760" alt="Capto_Capture 2019-03-23_12-20-19_pm" src="https://user-images.githubusercontent.com/43789/54865965-0a84f780-4d66-11e9-9c1f-bfed44a6f2e9.png">

@Srushtika @tomczoink why are we using an undocumented method definition?

@paddybyers @SimonWoolf should we perhaps modify the spec anyway to support three overloaded versions:

* `publish(String name, Object data)`
* `publish(Message message)`
* `publish(Message[] messages)`

In addition, @tomczoink I think the docs are wrong anyway.

`publish(String name, Object data)` should in fact be `publish(String name, Object data, String clientId, Object extras)`.   Now in languages like Javascript, which does not support named params, we may not want to support that, or perhaps we'd support it slightly differently as follows: `publish(String name, Object data, Object extraMessageAttributes)` would could then contain an arbitrary set of key/val pairs such as `publish('name', 'data', { clientId: 'foo', extras: { .. });`

My concern either way is that we have to continue to support new arguments / params for the publish method to:

* Support query params being added to the request to support, amongst other things, features like [wait for channel to become active](https://github.com/ably/wiki/issues/310).  Where do those params go?
* New message attributes, that in the first version of the method, will start to get unwieldy if they're defined in the method itself such as `publish(String name, Object data, String clientId, Object extras, String id, String someNewParam)`

Therefore, perhaps instead, we should only support three forms as follows:

* `publish(String name, Object data, Object params)`
* `publish(Message message, Object params)`
* `publish(Message[] messages, Object params)`

Thus if a user wants to do more than send a simple message with a name & data value, they need to instead send one or more message objects, and specify params separately.

WDYT @paddybyers @SimonWoolf?

**Comment by SimonWoolf** [comment]
> Thus if a user wants to do more than send a simple message with a name & data value, they need to instead send one or more message objects, and specify params separately.

:+1: agreed. (I don't see any point in having an `extraMessageAttributes` argument -- you're right, if someone wants extra message attributes like clientId, it's clearer to just pass in a Message).

Ably-js already supports exactly the three forms you've suggested, for REST channels at least -- the `params` are just sent as queryString parameters, a change I made for the quickAck work. (Not sure what we'd do with `params` for a realtime publish?).

**Comment by mattheworiordan** [comment]
Ok, so the problem we have then is that our client libraries do not all currently support this.

So we need to decide:

* Do we ensure our docs are consistent and use the more verbose and supported format: `publish(Message[] messages)` when publishing calling `publish` with anything other than `name` and `data`?  Or should we, where supported unofficially, use the shorter version.  My preference: using the longer `[msg]` version until it's officially supported, even if it looks a little odd.
* Do we get this change into all libs as soon as practicable within the 1.1 spec?  My preference: yes.  It's a tiny change and could be rolled out quite quickly I expect.
* Do we add `Object params` argument when doing above, or leave until later?  My preference: Do at the same time, and these params are added to the REST publish request as query params.  No need to worry about realtime as not applicable.

**Comment by paddybyers** [comment]
Which libraries don't already support `publish(Message message)` ?

**Comment by mattheworiordan** [comment]
> Which libraries don't already support publish(Message message) ?

I don't know, I assume most of them given it's not in the spec.

**Comment by mattheworiordan** [comment]
Sample of 3 - none of them:

https://github.com/ably/ably-python/blob/develop/ably/rest/channel.py#L41-L47
https://github.com/ably/ably-go/blob/develop/ably/rest_channel.go#L49-L62
https://github.com/ably/ably-ruby/blob/master/lib/ably/rest/channel.rb#L50-L79
