### ISSUE TITLE
Add help articles for 80016 and 80022

### ISSUE THREAD

**Issue by paddybyers** [ably/docs#655]
From customer comment:

> I’m tracking down an error witha code `80022` but cant find any documentation on it

```{
    "error": {
        "message": "Unable to find connection: aXLNjQD1NU_JbOnj. (See https://help.ably.io/error/80022 for help.)",
        "code": 80022,
        "statusCode": 410,
        "href": "https://help.ably.io/error/80022",
        "serverId": "frontend.77e9.1.us-east-1-A.i-090a80da2f5873e75"
    }
}
```

My comment:

> The error relates to comet connections, and it happens when the comet client directs a `/send` or `/recv` request to the system, and it arrives at a frontend different from the one that's hosting that connection. That's a legitimate thing in some circumstances, but
> (a) it should only happen if there has been a failure or deploy or scaling event affecting a frontend instance; and
> (b) it's not a fatal error as far as the connection is concerned - the transport will drop and a new transport initiated, and everything should just continue. There shouldn't be any error propagated back to you

Does that give you enough @tomczoink to create the skeleton of a support article pls?

**Comment by tomczoink** [comment]
Support articles can be found at https://support.ably.io/a/solutions/articles/3000096119 and https://support.ably.io/a/solutions/articles/3000089432
