### ISSUE TITLE
Default language selector doesn't seem to apply in docs

### ISSUE THREAD

**Issue by Srushtika** [ably/docs#659]
@tomczoink, see the screenshot below: 

<img width="1431" alt="Screenshot 2019-04-25 at 01 06 47" src="https://user-images.githubusercontent.com/5900152/56701352-8ae8a080-66f6-11e9-830a-2bc29cd22d83.png">

In the `authHeaders` client option definition, the first sentence is incomplete. Turns out the rest of the sentence is to be determined wrt the language selected, however, the 'default' option doesn't seem to apply at all, as you can see from the console. The other language options for which some other text exists applies as expected (Ruby in this case)

**Comment by tomczoink** [comment]
This is odd, investigating currently 🤔
