### ISSUE TITLE
Cipher API spec typo: withCipherKey()

### ISSUE THREAD

**Issue by paddybyers** [ably/docs#701]
Customer report:

> https://www.ably.io/documentation/realtime/encryption
>
> Should be this: ChannelOptions options = ChannelOptions.fromCipherKey(<Key>);
>
> Instead of this:

```
ChannelOptions options = ChannelOptions.withCipherKey(<key>);
Channel channel = realtime.channels.get("pin-aim-ice", options);
channel.subscribe(new MessageListener() {
  @Override
  public void onMessage(Message message) {
    System.out.println("Decrypted data: " + message.data);
  }
});

channel.publish('unencrypted', 'encrypted secret payload');
```

**Comment by tomczoink** [comment]
@paddybyers the spec from my understanding says we should use `withCipherKey` (https://docs.ably.io/client-lib-development-guide/features/#TB3), want me to change that as well to `fromCipherKey`?

**Comment by paddybyers** [comment]
can you check what the other libraries are doing?

**Comment by tomczoink** [comment]
@paddybyers I had a look and I think Java is the only one which has implemented this optional method.

**Comment by paddybyers** [comment]
> I think Java is the only one which has implemented this optional method.

ok, so there's a bug in the java library where it has the wrong method name? Can you raise an issue there pls?

**Comment by tomczoink** [comment]
#492
