### ISSUE TITLE
Spec for params option to rest channel.publish()

### ISSUE THREAD

**Issue by SimonWoolf** [ably/docs#737]

**Comment by SimonWoolf** [comment]
The problem here is RSL1h, and the various interpretations of it, which are a bit of a mess.

>  `(RSL1h)` Where the library language permits, the `Channel#publish(name, data)` method should provide an optional argument that allows the `clientId` value to be specified such as `Channel#publish('event', 'data', { clientId: 'John' })`, and/or the `extras` field to be specified such as `Channel#publish('event', 'data', { extras: { push: { 'key': 'value' } })`

AFAICT the only library that implements it as-written (where the publish takes an optional map that is mixed in to the message) is ably-ruby (not surprising since it looks like Matt added it in 2015, encoding what ably-ruby already did). Ably-js and ably-java do not implement it at all; if you want to include a clientId or extras you have to use the single-message-object form of publish (eg in ably-js, `publish({name: 'event', data: 'data', extras: {...}, clientId: 'John'})`). Ably-dotnet accepts a clientId as an optional extra argument, but if you want extras you need to use the Message form. Ably-ios and ably-php both accept both clientId and extras as optional arguments using the type to disambiguate -- which means that any json-encodable object (ios) / php array (php)  is interpreted as an `extras`.

Which means the approach I've taken in ably-js (adding an extra argument for qs params) will only work nicely in ably-js, ably-java, and ably-dotnet. In ably-ruby it'd get confused with the attributes argument; in ably-ios and ably-php it'd get confused with the extras argument. 

One possible conclusion is that the separate-argument forms (name, data, ...) are now hopelessly different across the different client libs, and we should allow the params argument only for the `publish(Message)` / `publish(Message[])` forms...

@mattheworiordan @paddybyers wdyt?

**Comment by paddybyers** [comment]
> we should allow the params argument only for the `publish(Message)` / `publish(Message[])` forms...

agreed.

And the form that doesn't take a `Message`, but `name` and `data`, should IMO be limited to just that. Otherwise it's just an arbitrary set of other fields, and an arbitrary set of precedence rules when disambiguating the possibilities when looking at what's actually been passed.
