### ISSUE TITLE
Push docs have a missing method description

### ISSUE THREAD

**Issue by Srushtika** [ably/docs#752]
In our docs, the method `get(PushChannelSubscription)` is listed in the API reference sidebar but the description is missing. 
https://www.ably.io/documentation/general/push/admin#push-channel-sub-get
See screenshot below:
<img width="1000" alt="Screenshot 2019-10-28 at 13 50 07" src="https://user-images.githubusercontent.com/5900152/67685596-45e74480-f98d-11e9-86dd-99e304565bcc.png">

**Comment by tomczoink** [comment]
From what I can tell the get method doesn't actually exist so I should remove this. Just to check before I do am I right @paddybyers ?

**Comment by paddybyers** [comment]
There is no `get()` method, because there's no subscriptionId or anything else definitive that you could use to retrieve a single subscription. To get details on an existing subscription, you have to `list()` with relevant parameters.
