### ISSUE TITLE
Ably's JSBin fork needs updating to support more modern Javascript

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#756]
See related issue https://github.com/ably/jsbin/issues/2.

Not directly related, but we could in future consider adding server-side code block support too with Repl.it - https://github.com/ably/docs/issues/690.

┆Issue is synchronized with this [Jira Bug](https://ably.atlassian.net/browse/DOC-130) by [Unito](https://www.unito.io)

**Comment by kennethkalmer** [comment]
@mattheworiordan, @fliptopbox also mentioned codepen.io as something to have a look at and they have an API as well - https://blog.codepen.io/documentation/prefill/

**Comment by fliptopbox** [comment]
I recommend we move to codepen for a number of reasons, I'll write them down.

**Comment by mattheworiordan** [comment]
> I recommend we move to codepen for a number of reasons, I'll write them down.

You've not written them down :). Can you?

Interestingly I see Google us JSFiddle, which is quite neat, see https://developers.google.com/maps/documentation/javascript/adding-a-google-map and specifically https://docs.jsfiddle.net/api/display-a-fiddle-from-post, where a POST creates the fiddle live.  

This IMHO is elegant because @kennethkalmer we would no longer need to publish JSBins / Codepens / anything else at build time, and instead generate the code on demand at runtime.   Far slicker, and it works for Google 👍

**Comment by mattheworiordan** [comment]
I see https://blog.codepen.io/documentation/prefill/ has a similar POST option. 

@fliptopbox do we know if Codepen is the most popular?  Can we research which is the most popular before we dive in?

**Comment by fliptopbox** [comment]
Yup, there is a discovery document on its way, that looks at Codepen from various angles.
We should have a working draft on Wednesday late afternoon, I will be sure to ping your for feedback.
