### ISSUE TITLE
Reactor HTTP Endpoint changes breaks docs + tutorials

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#765]
The new Reactor Integration work for IFTT, Zapier and Cloudflare has gone live.  As part of this work, we also consolidated Webhooks & HTTP Custom Endpoints into just "HTTP Endpoint".

We have a number of issues now:

* \[x] The help copy under "Single request / Batch request" is incorrect. It states "Batch request will send events triggered concurrently in the same request" which is not true.  It batches requests based on a time period of 1 second, and with a max number of messages per envelope.  The docs  at [https://www.ably.io/documentation/general/webhooks](https://www.ably.io/documentation/general/webhooks) describe how this works.
* \[x] The "Enveloped" checkbox I believe does not apply in Batch mode (old style webhooks).  I think the Envelope is required given they are batched.  @SimonWoolf can you confirm?
* \[ ] I am not sure it makes sense to put "Request Mode" under headers, when enveloped & encoding options sit below the source info.  I think how the data is delivered should be grouped together.
* \[x] The documentation for Webhooks is now all wrong - see [https://www.ably.io/documentation/general/webhooks](https://www.ably.io/documentation/general/webhooks)
* \[x] The tutorials for Webhooks etc. should be reviewed. as I suspect they are also now partly wrong.
* \[ ] The help copy about how Envelopes works also needs to be revisited now
* \[x] I question whether we should call this HTTP Endpoint in Reactor and just call this Webhooks instead.  Customers are far more familiar with that concept, and our docs all refer to Webhooks.  Review the Reactor page too www.ably.io/reactor.
* \[x] The links inside the modal to find out more, or get help on a field, should open new tabs.  That is when opening a new tab makes sense because the user is in the middle of a form set up process.
* \[x] I think Webhooks should actually come first in the New REactor window because then you have 1 Webhook, two API Integration platforms IFTT & Zapier, and the rest that follow are all functions.
* \[x] The text "The URL of your server we will POST a summary of events to in JSON format" is wrong given you can choose a different encoding (MsgPack).
* \[x] Scrolling is broken in the new reactor event modal when it is higher than the window height, you cannot scroll down to the bottom of the modal.
* \[ ] When using in API Consumer, I think we should make it clear that batch request mode is not supported, as opposed to just hiding that option.

Whilst looking at this, we may additional want to consider:

* [Add docs to reflect new test feature for rules](https://github.com/ably/docs/issues/625)
* [Add fromEnvelope](https://github.com/ably/docs/issues/667)

┆Issue is synchronized with this [Jira Bug](https://ably.atlassian.net/browse/DOC-132) by [Unito](https://www.unito.io)

**Comment by SimonWoolf** [comment]
> The "Enveloped" checkbox I believe does not apply in Batch mode (old style webhooks). I think the Envelope is required given they are batched. @SimonWoolf can you confirm?

Yeah - traditional batched webhooks have their own custom structure https://www.ably.io/documentation/general/webhooks#example-channel-message different from all the other rules for historical reasons, and that structure doesn't take an enveloped option
