### ISSUE TITLE
Consider migration to generic documentation site generator

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#772]
See https://docusaurus.io/docs/en/doc-markdown

A lot of what we have built, exists in this open source library.

Long term, we may be better off contributing to that repository and benefiting from other community contributions.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/DOC-133) by [Unito](https://www.unito.io/learn-more)

**Comment by tbedford** [comment]
Docusaurus 2 is indeed very capable. I wrote up some more notes on it (and some other systems) in "
Evaluation of documentation tooling" in our Confluence. I will close this issue as in short to medium term we'll improve our current toolchain.
