### ISSUE TITLE
Broken link in max rate limits doc

### ISSUE THREAD

**Issue by CharStephens** [ably/docs#782]
https://support.ably.io/support/solutions/articles/3000082527-understanding-how-instantaneous-max-rate-limits-are-calculated-and-enforced-

Under 'Further Reading', 'Read about all limits that exist on accounts' is broken and directs to [this](http://f%20you%20would%20like%20to%20see%20the%20exhaustive%20and%20up%20to%20date%20list%20of%20all%20standard%20limits%20on%20accounts%2C%20please%20see%20the%20connection%2C%20channel%2C%20message%20and%20rate%20limits%20article%20if%20you%20are%20not%20sure%20what%20package%20you%20need%2C%20please%20see%20our%20article%20that%20describes%20how%20you%20can%20calculate%20what%20package%20you%20need%20based%20on%20your%20requirements.%20if%20you%20have%20received%20an%20email%20about%20a%20limit%20you%20have%20neared%20or%20hit%2C%20please%20see%20the%20article/) the correct link is [this](https://support.ably.io/support/solutions/articles/3000053845-do-you-have-any-connection-message-rate-or-other-limits-on-accounts-)

**Comment by tomczoink** [comment]
The link has been fixed.
