### ISSUE TITLE
Update Channel Parameters page to use setOptions

### ISSUE THREAD

**Issue by QuintinWillison** [ably/docs#803]
A note has been added to `RSN3c` for 1.2 stating that `Channels#get(channel, options)` is being soft-deprecated in favour of `Channel#setOptions`.

The "Rewind example with an Ably client library" should be updated to use the newer API.

[/content/realtime/channel-params.textile](https://github.com/ably/docs/blob/master-1-2/content/realtime/channel-params.textile)

**Comment by MarkWoulfeAbly** [comment]
This example was updated to use setOptions for the 1.2 deltas release
