### ISSUE TITLE
Infinite redirect on Feature Spec page when switching versions

### ISSUE THREAD

**Issue by JackUkleja** [ably/docs#829]
Think the steps I took were:
* Visit https://www.ably.io/documentation/client-lib-development-guide/features
* Switch to 0.8
* Click hyperlink in notification about it not being latest version of doc.

I _think_ this is when redirect loop started.

Interestingly seems to persist between sessions (!) i.e. going to 
https://www.ably.io/documentation/client-lib-development-guide/features
redirects to 
https://www.ably.io/documentation/client-lib-development-guide/versions/v0.8/features
(even though the first time I visited https://www.ably.io/documentation/client-lib-development-guide/features this did not happen)

Using latest version of Chrome on latest version of Windows 10.

**Comment by mattheworiordan** [comment]
I am afraid I think this is not a docs issue.  If you go to https://docs.ably.io/client-lib-development-guide/features/ and reproduce above, this does not happen.

As such, this is in fact a website issue arising in the website handling over version changes.

In addition, we need to fix the version drop down.

![screenshot_2020-03-02_06-15-37_pm](https://user-images.githubusercontent.com/43789/75705113-9e6b7d00-5cb2-11ea-82e7-007fa6692276.png)

@JackUkleja all issues should be tagged too.

**Comment by mattheworiordan** [comment]
@JackUkleja please add a comment in regards why an issue is closed, specifically in this case because it was moved to WEB-188.
