### ISSUE TITLE
Add info on wildcards in channel rules documentation

### ISSUE THREAD

**Issue by Srushtika** [ably/docs#836]
Currently, [we only talk about resources and wild cards in docs relating to authentication and capabilities only](https://www.ably.io/documentation/core-features/authentication#wildcards). However, this also applies to channel rules, which means we should also add this info in those pages.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/DOC-207) by [Unito](https://www.unito.io)

**Comment by SimonWoolf** [comment]
> However, this also applies to channel rules

no it doesn't

**Comment by mattheworiordan** [comment]
I am not sure what you mean Srushtika? Can you be more specific about what is lacking?

**Comment by Srushtika** [comment]
@mattheworiordan Simon has verified that wildcards don't apply to channel rules. So, closing this issue.

**Comment by markcoxsmith** [comment]
Reopening this issue as had another customer ask about this - might be worth explicitly mentioning this in the docs. Will be doing so in the KB
