### ISSUE TITLE
Document how to renew tokens and resume with continuity for SSE

### ISSUE THREAD

**Issue by paddybyers** [ably/docs#837]
If an SSE connection requires a new token, then that's a new URL and therefore a new `EventSource`. Customers need to know how a new `EventSource` can resume with continuity from an existing connection.

We need this process to be written up, ie some explanation together with a code snippet of how to make it work. Then it probably drops quite naturally somewhere into the SSE documentation.

**Comment by SimonWoolf** [comment]
Notes for someone to write up docs from:
- Many eventsource implementations (in particular browsers) do not expose the current lastEventId on the EventSource object. So if might want to resume with a new EventSource object, eg cos you're using token auth, you need to keep track of the lastEvent yourself
- In most implementations, the Message object you get will include a `lastEventId` property as well as a `data` property
- keep track of the last one of those received, add it as a `lastEvent` querystring param when you reconnect
eg (nb this is off the top of my head and untested):
```js
let lastEvent, eventSource;
const connectWithToken = token => {
  eventSource = new EventSource(`https://realtime.ably.io/sse?v=1.1&access_token=${token}&channels=${channel}${lastEvent ? '&lastEvent=' + lastEvent : ''}`);
}
let eventSource = 
eventSource.onmessage = msg => {
  console.log(msg.data); // the Ably Message object
  lastEvent = msg.lastEventId;
}
eventSource.onerror = msg => {
  const err = JSON.parse(msg.data);
  const isTokenErr = err.code >= 40140 && err.code < 40150;
  if(isTokenErr) {
    const newToken = <get new token>
    connectWithToken(newToken);
  } else {
    // ...
  }
}
```

**Comment by mattheworiordan** [comment]
> In most implementations, the Message object you get will include a lastEventId property as well as a data property

Why "most implementations"?  When not?  Should we explain that to a customer.

> } else {
>    // ...
>  }

Could we offer some advice on terminal failures so that they don't just reattempt connection?  

> eventSource.onmessage = msg => {
>  console.log(msg.data); // the Ably Message object
>  lastEvent = msg.lastEventId;
> }

Did we never end up sending the token renewal request inband so that they can get a token, and then explicitly reconnect based on the last message, giving them the ability to effectively not be disconnected?

**Comment by SimonWoolf** [comment]
> Why "most implementations"? When not? Should we explain that to a customer.

Having checked the standard it is in fact required, so should be the case for all implementations. (I guess I was hedging as I've not played around with really any implementations other than the browser & node ones, so have no idea which ones stick quite closely to the browser spec vs doing their own completely-different API on top of the protocol)

> Could we offer some advice on terminal failures so that they don't just reattempt connection?

I'm sure we could. It's missing from the code snippet above because that I didn't write it as a fully-featured example app to demonstrate all aspects of using SSE with Ably, just to show how token reauth works

> Did we never end up sending the token renewal request inband so that they can get a token, and then explicitly reconnect based on the last message, giving them the ability to effectively not be disconnected?

No. Inband reauth is part of the [Ably.Eventsource SDK plan](https://github.com/ably/wiki/issues/408), but it was never part of the [the spec for normal SSE support](https://github.com/ably/wiki/issues/185) (in fact third bullet point of that explicitly stated token reauth would be "If the connection is closed or rejected with an auth failure, get a new token and reopen with lastSerial").

If it had been, I think I'd have argued against it that since customer would need to handle the closed-with-40142 case anyway, the principle that it should be simple for the customer to implement would favour only having one code path for reauth rather than two. (That consideration doesn't apply to the Ably.Eventsource SDK plan which is why we were planning inband reauth for that -- at least, that was my understanding)

**Comment by paddybyers** [comment]
Didn't we enable token expiry warnings though?

**Comment by SimonWoolf** [comment]
> Didn't we enable token expiry warnings though?

No. I filed an issue for it at https://github.com/ably/realtime/issues/2779 on behalf of split, but we never decided anything or scheduled it in

**Comment by paddybyers** [comment]
> we never decided anything or scheduled it in

Isn't it just a 1-liner?

**Comment by SimonWoolf** [comment]
> Isn't it just a 1-liner?

Depends how we decide to do it, which we hadn't decided yet. The two possibilities we've discussed were:
1. an `auth` sse event delivered (question: unconditionally, or only if you supply a qs param?)
2. a `[meta]tokenevents` metachannel you can subscribe to to get an expiry warning - bit more complex for SSE, but has the advantage of automatically generalizing to new transports we add (and existing ones like pubnub, mqtt etc.), and being a uniform way of getting them across all (non-ably-proprietary) transports

**Comment by mattheworiordan** [comment]
I would argue we could support both to simplify SSE, but I don't mind if you'd prefer just one way, and then do (2).

**Comment by mattheworiordan** [comment]
@paddybyers we promised to send over some code examples / docs in regards to token auth to Split last week.  Can we aim to have something decided fro COP of Friday we can communicate so that we're guiding them on their implementations?

**Comment by paddybyers** [comment]
## Token renewal for SSE connections

### Overview

When using an SSE connection to subscribe to Ably channels, such as through the `EventSource` API, the Ably credentials for the connection are included as a parameter in the connection URL. Typically the credentials will be an [Ably token](https://www.ably.io/documentation/core-features/authentication#token-authentication), included as an `accessToken` param.

The SSE protocol and `EventSource` API are designed so that a dropped connection is resumed transparently; the client implementation will reconnect and supply a `lastEventId` param that ensures that the resuming connection delivers any events that have arisen since the connection was dropped. Ably uses this mechanism to reattach all channels in a new connection to the exact point that had been reached in the prior connection.

When a token expires the connection will end. However, the default `EventSource` behaviour of automated reconnection will not work, because the (expired) credentials are part of the connection URL. What is needed is for a new connection to be established, with an updated `accessToken`. The question then arises as to how to do that with continuity - that is, how to establish a new connection but supply the correct `lastEventId` so that the new connection resumes from the point that the prior connection became disconnected.

### Implementation

Implementing transparent connection resumes when tokens require renewal requires a few different steps.

#### Detecting token expiry

When a connection is closed as a result of any error (that is, it's not just a dropped connection), then the `onerror` event will occur on the `EventSource`, and the `data` attribute of the event will contain an Ably error body which contains information about the nature of error. In the case of a token error - that is an error arising from a problem with the token that can be retried with a new token - then the `code` in the error body indicates that. Token errors have a `code` in the range `40140 <=code < 40150`.

In the future we plan to send an event on the connection that indicates that the token will expire imminently, which will allow a new connection to be established prior to the closure of the previous connection.

#### Specifying the `lastEvent`

Each message received will have a `lastEventId` attribute containing the last `id` of any message received on the connection. When constructing a new connection, this value can be specified as a `lastEvent` param.

#### Example

```js
let lastEvent, eventSource;

// establish a connection with a given token
const connectWithToken = token => {
  const lastEventParam = lastEvent ? ('&lastEvent=' + lastEvent) : '';
  eventSource = new EventSource(`https://realtime.ably.io/sse?v=1.1&accessToken=${token}&channels=${channel}${lastEventParam}`);
}

// handle incoming messages
eventSource.onmessage = msg => {
  lastEvent = msg.lastEventId;
  // ... normal message processing
}

// handle connection errors
eventSource.onerror = msg => {
  const err = JSON.parse(msg.data);
  const isTokenErr = err.code >= 40140 && err.code < 40150;
  if(isTokenErr) {
    const newToken = <get new token>
    connectWithToken(newToken);
  } else {
    // ... any other event handling
  }
}
```
