### ISSUE TITLE
auth docs don't mention auth.tokenDetails property

### ISSUE THREAD

**Issue by SimonWoolf** [ably/docs#839]
https://www.ably.io/documentation/rest/authentication only mentions a clientId property, not tokenDetails. https://docs.ably.io/client-lib-development-guide/features/#RSA16

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/DOC-54) by [Unito](https://www.unito.io)

**Comment by SimonWoolf** [comment]
Just realised RSA16 is part of the 1.1->1.2 changelog, so tagging this v1.2

**Comment by tbedford** [comment]
Now mentioned, albeit it briefly. Lots more info here though:

https://ably.com/docs/api/rest-sdk/authentication#token-details
