### ISSUE TITLE
Address 1.2 API version sync in examples

### ISSUE THREAD

**Issue by QuintinWillison** [ably/docs#848]
See @SimonWoolf's comment [here](https://github.com/ably/docs/pull/843#pullrequestreview-384134783).

**Comment by mattheworiordan** [comment]
Is this issue still needed given https://github.com/ably/docs/issues/854, https://github.com/ably/wiki/issues/419 and https://github.com/ably/docs/pull/856.

As an aside, please remember to label issues, and include a small description of the scope of the issue.  I am not clear what "resolved" would look like for this issue.
