### ISSUE TITLE
Docs static site does not reflect how tutorials are rendered on the website

### ISSUE THREAD

**Issue by Srushtika** [ably/docs#863]
We recently updated our tutorial pages to show various tutorials as steps. As part of this, there's a lot of metadata that goes into the textile files which automatically gets rendered by the website repo. However, currently, there's no way to view how any tutorial will look on the final website (with all that metadata) unless the changes are pushed to a branch and deployed via Heroku. 

We need a better preview site so all the changes can be done and tested locally.

┆Issue is synchronized with this [Jira Maintenance](https://ably.atlassian.net/browse/DOC-50) by [Unito](https://www.unito.io)

**Comment by mattheworiordan** [comment]
@Srushtika renaming title "Docs preview site is no longer suitable given the new tutorial page structure" as I think that's far too broad a description of the problem.  

> We need a better preview site so all the changes can be done and tested locally.

The static site rendered by this docs repo needs to reflect the logic used to display tutorials on the website.
