### ISSUE TITLE
Client SDKs should gracefully handle non-JSON/MsgPack responses

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#874]
If a client SDK receives an error response from Ably that happens to be in an unexpected format such as HTML or text, it should handle that gracefully.

See https://github.com/ably/ably-go/issues/154 an issue that recently came up.

Whilst the SDKs should handle this anyway, I think it would be sensible to make this explicit so that there is test coverage over it.

Related tickets in proxy layers https://ably.atlassian.net/browse/INF-153, https://ably.atlassian.net/browse/INF-167

**Comment by QuintinWillison** [comment]
Historical breadcrumbs re [ably-go](https://github.com/ably/ably-go):

- fixed (April 2020): https://github.com/ably/ably-go/issues/154
- related (January 2020): https://github.com/ably/ably-go/issues/127

**Comment by mattheworiordan** [comment]
@QuintinWillison can you propose a spec item for this to reflect what was done in Go?

**Comment by QuintinWillison** [comment]
Sure. Internal story [SDK-13](https://ably.atlassian.net/browse/SDK-13) created so it can be managed in the backlog.
