### ISSUE TITLE
Channel metadata API ref incorrectly describes the occupancy object

### ISSUE THREAD

**Issue by Srushtika** [ably/docs#877]
This was feedback given to us from an enterprise customer. It seems that we are not describing the occupancy object accurately in the Channel metadata API reference. See: https://www.ably.io/documentation/realtime/channel-metadata#occupancy

The #of publishers, subscribers, etc are children of the `metrics` object, which in turn is a child of the `occupancy` object. This needs to be fixed.

┆Issue is synchronized with this [Jira Bug](https://ably.atlassian.net/browse/DOC-48) by [Unito](https://www.unito.io)

**Comment by tomczoink** [comment]
We should also update the open-api spec, as that also is missing the metrics step.

**Comment by MarkWoulfeAbly** [comment]
@tomczoink do you have a good idea of what the fix for this would look like? I've not made any API reference changes thus far and not sure what the solution here is.

**Comment by tomczoink** [comment]
Currently we don't mention that there's a `metrics` object which contains the Occupancy details, and is within the `occupancy` object. Actual structure is:

```
{
	"name": "recommendation",
	"channelId": "recommendation",
	"status": {
		"isActive": true,
		"occupancy": {
			"metrics": {
				"connections": 1,
				"publishers": 1,
				"subscribers": 1,
				"presenceConnections": 1,
				"presenceMembers": 0,
				"presenceSubscribers": 1
			}
		}
	}
}
```

We incorrectly indicate it's:

```
{
	"name": "recommendation",
	"channelId": "recommendation",
	"status": {
		"isActive": true,
		"occupancy": {
				"connections": 1,
				"publishers": 1,
				"subscribers": 1,
				"presenceConnections": 1,
				"presenceMembers": 0,
				"presenceSubscribers": 1
		}
	}
}
```
