### ISSUE TITLE
history and get Request arguments

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#88]
In the current definition in the client libs of `get` & `history` methods, it looks like the following:

`.get = function(/* params, callback */)`
or in Ruby
`get(options = {}, &block)`

When writing the docs, we following the format:

* Method definition
* Parameters
* Return value

When one of the params is a set of params that needs to be documented separately, the options are to document them inline or to document them below Parameters, see http://docs.ably.io/realtime/history/ for an example. The problem with the former is both space and the fact that you then need to use HTML as opposed to Textile markup.

I would prefer that we then broke down the options beneath like we have at http://docs.ably.io/realtime/history/, however I really don't like the fact that the title is Parameters yet the argument is called `params` as well in most languages (I use the more common options in Ruby).

We have a few options here:

* Rename the heading Parameters to Arguments in all cases thus making it easier to have a separate ` params options` heading for example.  I think argument is fine, except that technically they are not arguments (arguments are received) whereas parameters are sent when invoking a method / function.
* Avoid using a generic `params` parameter in method definitions for all languages and prefer something like `query`, `filters`, or `options` even.  Calling it params, when it itself is a param, is arguably wrong.
* I could try and build a new style that accommodates options within a parameters definition, but I do think it will look shit.

@paddybyers @SimonWoolf @tcard any thoughts?

**Comment by paddybyers** [comment]
> technically they are not arguments (arguments are received)

I think they are arguments.

**Comment by mattheworiordan** [comment]
Well according to https://en.wikipedia.org/wiki/Parameter_(computer_programming)#Parameters_and_arguments it's not:

> The terms parameter and argument are sometimes used interchangeably, and the context is used to distinguish the meaning. The term parameter (sometimes called formal parameter) is often used to refer to the variable as found in the function definition, while argument (sometimes called actual parameter) refers to the actual input passed.

So technically they are parameters as they are part of the definition of the method.

**Comment by tcard** [comment]
I wouldn't like changing Parameters to Arguments. I would prefer to rename all `params` to `options` or `query`, depending on the use case.

**Comment by paddybyers** [comment]
OK, so perhaps the name of the  `params` formal parameter just needs to be qualified, if those are in fact the parameters of part of the operation. For example we have `cipherParams`, which is a single param of one method, but contains the params for a constituent operation.

SO are these the `queryParams`, or `historyParams`, or even `historyOptions` ?

**Comment by mattheworiordan** [comment]
> technically they are not arguments (arguments are received)

Btw. that was a typo, I meant arguments are sent from the caller

**Comment by mattheworiordan** [comment]
I'd be happy with `historyParams` and then `getParams` in the case of `get`, the more explicit the better, and if we later introduced a type for this, it would make life easier too.  @tcard you happy with that as well?

**Comment by tcard** [comment]
`history(historyParams, callback)`? So there's a `history` param named `callback` and a `history` param called `historyParams`? Not so pretty... In this case `query` sounds better to me. (It is named like that in iOS already.)

**Comment by mattheworiordan** [comment]
@tcard true, in fact we've removed some of this duplication previously in the iOS library where we had the method name prefixed in the params.  If we introduced a type that is specific to the method then we would name it accordingly, but as you say, as a param name, it's unnecessary because of the context.

So 
`history(Params[] query, callback)` and `get(Params[] query, callback)`?

**Comment by paddybyers** [comment]
I would prefer `options` to `query` here

**Comment by mattheworiordan** [comment]
Sure, I have no objection to that, also means I don't need to change the Ruby lib :)
