### ISSUE TITLE
Use the website style sheets and header & footer during static site builds

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#881]
Here's a crazy idea to simplify how documentation is delivered.

1. When this static site is built, pull in standard CSS, JS, page headers and footers that are pulled in over HTTP from www.ably.io.  This will ensure that this static site can be consistent with the main website by sharing styles, and common HTML elements.
2. Use Javascript to alter the header & footer when it detects it's on the primary domain and logged in (via a cookie / Ajax request / etc).
3. Move all documentation logic out of the website completely.
4. Call out to a local path for keys, so when served via www.ably.io/documentation, it will use a demo key if not logged in, and actual keys if logged in.  When running in any other domain, it will detect that and call out to www.ably.io separately and get a demo key only (security reason should prevent us from allowing API keys to leak outside of the website domain)
5. Style this static site based on the current website's documentation, and then build from there.
6. Publish this site a static site, which is served up by www.ably.io/[documentation|tutorial] which in turn proxies all requests to the static site and caches the requests for a short period.

Why do this:

- Docs developers can work on this site separate from the primary website without worrying a change will break the main website
- This encapsulates all documentation and tutorials and code samples as a "product"
- Reduce duplication of work (all features in https://docs.ably.io/client-lib-development-guide/documentation-formatting-guide/ are duplicated in the main website)
- This should allow docs to be more lightweight
- This should allow the website to be more lightweight
- Even if the website changed, and the static site was slightly behind, it would simply require the static site to be republished, which would pull in the latest website assets as part of the build, and voila.  It can be rolled back if that breaks things.
- Freedom!  
- Happiness 😸 

Caveat:

- There may be dependencies that makes this harder than we imagine
- There are things like shared tracking code / partials / customisations of the tempalte that may make this really hard to do in practice

WDYT @JackUkleja @dpiatek @MarkWoulfeAbly

┆Issue is synchronized with this [Jira Maintenance](https://ably.atlassian.net/browse/DOC-46) by [Unito](https://www.unito.io)

**Comment by MarkWoulfeAbly** [comment]
When we're referring to the 'static site' are we talking about https://docs.ably.io/?

Assuming we are then I would be a big fan of this change, having the static/staging site mimick the actual live version is one of the things I was going to ask for. 

Additionally, the de-coupling of the docs and the main website process would hopefully give me more control and autonomy over documentation updates without having to involve engineers too much, especially for things that are just content updates.

**Comment by dpiatek** [comment]
> When this static site is built, pull in standard CSS, JS, page headers and footers that are pulled in over HTTP from www.ably.io. This will ensure that this static site can be consistent with the main website by sharing styles, and common HTML elements.
> Use Javascript to alter the header & footer when it detects it's on the primary domain and logged in (via a cookie / Ajax request / etc).

I'm worried about two things with this solution:
- how maintainable will this be long term as this is still a pretty hard coupling between the main and docs sites (how do we not break the docs site when we make changes to the nav/footer? how do we manage the global CSS/JS thats needed to make them work? how do we handle specific, logged in/account data shown in these?)
- the code that we will scrape will be bloated and will put a minimum threshold on how fast the docs website will be

So in a way general way, I'm wondering what's short term vs long term trade off here and if it's worth it. 

I was also thinking, what if the docs are a completely new thing (I'm assuming you are thinking about rebuilding here based on point no 5)? Everything is built new, with a simpler but similar nav (so they are consistent brand wise but clearly different so there is no confusion where you are on the site). All other interactions are either API (for complex stuff, if needed) or cookie (for simpler stuff, assuming same domain). Let's say we also we have some style inconsistencies that we eventually fix. Isn't having those a good trade off for being able to work almost completely independently on the docs?

Eventually we will want a styleguide for components that different product initiatives within the company will want to follow, so why not start here? 

On a slightly related note, I think also if we would make this a React/Gatsby or React/Next.js project it would be easier to find contractors/freelancers to help build it as it's a way more popular stack among front-end developers then Rails. And you get a person who does it essentially full-stack.

**Comment by mattheworiordan** [comment]
> how maintainable will this be long term as this is still a pretty hard coupling between the main and docs sites (how do we not break the docs site when we make changes to the nav/footer? how do we manage the global CSS/JS thats needed to make them work? how do we handle specific, logged in/account data shown in these?)

As the docs site should statically build, and not depend on the Ably website at runtime, changes to the nav/footer won't be reflected immediately in the docs, and that's OK.  When the next docs build is done, if something is broken, we'll know because we'll see it at build time.

> how do we handle specific, logged in/account data shown in these?

We keep it simple and have a documented endpoint, such as `/identity`, which returns all info needed in a single JSON request to render the docs.  That way, we can ensure there is a well known API, with test coverage, that the docs repo can depend on.

> the code that we will scrape will be bloated and will put a minimum threshold on how fast the docs website will be

That's an engineering problem that you will need to fix.  I never suggested we do this inefficiently.  I do think it will be done in stages though, and on day one, there will likely be some bloat.  But that's not the design, it's part of the journey.

> I was also thinking, what if the docs are a completely new thing (I'm assuming you are thinking about rebuilding here based on point no 5)? 

Absolutely not.  We should take the CSS & JS from the website that is used for docs, move it out of the website, and into this repo.  Remember the docs content is just rendered as HTML now on the Ably website, so a lift and shift is quite feasible.  Why would we rebuild it from scratch?  THere's a shit load of engineering that does a lot of good stuff.

> verything is built new, with a simpler but similar nav (so they are consistent brand wise but clearly different so there is no confusion where you are on the site). All other interactions are either API (for complex stuff, if needed) or cookie (for simpler stuff, assuming same domain). Let's say we also we have some style inconsistencies that we eventually fix. Isn't having those a good trade off for being able to work almost completely independently on the docs?

Perhaps.  Although equally, perhaps we can share the header & nav if we build the website in a way that allows it to be shared and not leak CSS and JS unnecessarily into other parts of the site.

> Eventually we will want a styleguide for components that different product initiatives within the company will want to follow, so why not start here?

I agree on styleguide, but the docs repo should not be dependent upon components the web team build.  If we do that, we're back to square one.  This site, should have creative direction steer from Jamie, but ultimately IMHO, been maintainable almost entirely separately.

> On a slightly related note, I think also if we would make this a React/Gatsby or React/Next.js project it would be easier to find contractors/freelancers to help build it as it's a way more popular stack among front-end developers then Rails. And you get a person who does it essentially full-stack.

Sure, and if we rebuilt the Ably realtime stack in Go, we'd find more engineers to work on hard distributed problems, and if we rebuilt the orchestration layer in Go, we'd also find it easier.  However, the business would slow down rapidly as we spend a LOT of time trying to re-engineer 6+ years of documentation engineering just so that we can get a JS dev.  The site is just a static site builder, so almost all of the changes are Textile, a small amount are CSS and HTML, and an even smaller amount are Ruby.  There is no Rails, and we have a Ruby engineering team.  So sure, I get your point, but I don't see why we'd do that in practice.

**Comment by mattheworiordan** [comment]
P.S. Just for the avoidance of doubt, this is clearly low priority, unless we believe this is currently blocking our goal of providing great DX and improved docs.  Great docs & DX is about the content, the journeys, the quality of the info, etc.  And whilst it would be nice to in time figure out if this docs repo should operate entirely independently of the website from an operational perspective, clearly it's not a priority when we are able to improve our docs, tutorials, user flows today, without making any fundamental changes.  Once @MarkWoulfeAbly has worked with this repo for a few months, we should revisit this then coming at it with operational understanding of where the shortcomings are.

**Comment by fliptopbox** [comment]
> pull in standard CSS, JS, page headers and footers
Here is another crazy idea, Web Components will allow us to do that.

**Comment by dpiatek** [comment]
Thanks for clarifying @mattheworiordan. I think decoupling the docs from the website is a worthy goal that could help with our lead times for delivering stuff in the docs; the recent updates showed that it's not exactly straightforward to do bigger changes.

> Eventually we will want a styleguide for components that different product initiatives within the company will want to follow, so why not start here?
> 
> I agree on styleguide, but the docs repo should not be dependent upon components the web team build. If we do that, we're back to square one. This site, should have creative direction steer from Jamie, but ultimately IMHO, been maintainable almost entirely separately.

So the idea here is the styleguide gives design guidance on a component level but does not dictate the implementation (so it shows how a nav dropdown should look and behave but that's all), exactly to allow separate maintenance.

> On a slightly related note, I think also if we would make this a React/Gatsby or React/Next.js project it would be easier to find contractors/freelancers to help build it as it's a way more popular stack among front-end developers then Rails. And you get a person who does it essentially full-stack.
>
> Sure, and if we rebuilt the Ably realtime stack in Go, we'd find more engineers to work on hard distributed problems, and if we rebuilt the orchestration layer in Go, we'd also find it easier. However, the business would slow down rapidly as we spend a LOT of time trying to re-engineer 6+ years of documentation engineering just so that we can get a JS dev. The site is just a static site builder, so almost all of the changes are Textile, a small amount are CSS and HTML, and an even smaller amount are Ruby. There is no Rails, and we have a Ruby engineering team. So sure, I get your point, but I don't see why we'd do that in practice.

Sorry, I'd understood wrongly that you are considering a rewrite. Wasn't thinking of a full re-engineering either, just using JS to render & build (so keeping the textile and the idea on how it works, just simplifying the stack, making it familiar to a wider group of people). Understand that's not what were after here though.

**Comment by mattheworiordan** [comment]
> I think decoupling the docs from the website is a worthy goal that could help with our lead times for delivering stuff in the docs; the recent updates showed that it's not exactly straightforward to do bigger changes.

Perhaps.  Although can we establish what made it slow?  
I am not convinced it being part of the website is actually the major problem.  I am happy to be enlightened though.  Additionally, we are actively moving all content out of the docs repo and into the CMS, for exactly this reason.   

> Wasn't thinking of a full re-engineering either, just using JS to render & build (so keeping the textile and the idea on how it works, just simplifying the stack, making it familiar to a wider group of people)

Well when you say wider group, who is that wider group?  Our maintainers of web assets use Ruby currently.  Sure, perhaps JS more generally is more widely known, but so is PHP :)

> Here is another crazy idea, Web Components will allow us to do that.

Sure, if we believe that won't have any negative impacts from an SEO / maintainability / performance perspective.  I don't know the answer to that, but I suspect needing a web compontent to be pulled in before the page can be rendered may not work so well for us.  In addition, if someone changes how the web component works, it could break sites (like docs) that depend on these web components.  

Personally I like the idea of each being statically generated so that changes made in other web assets (like the main website) cannot break other sites at runtime.  If a website change broke the docs site, then the docs team could not roll back.  They would be helpless and have to wait for the web team to fix it.  

On a separate note @dpiatek, I think whatever we do for standardised headers & footers, should be considered with the CMS content.  We want the CMS content to be as lightweight as possible, so ideally the CMS content would share headers & footers, and then otherwise have lightweight CSS & JS for the content areas to keep the pages light and fast.

**Comment by dpiatek** [comment]
> Perhaps. Although can we establish what made it slow?
> I am not convinced it being part of the website is actually the major problem. I am happy to be enlightened though. Additionally, we are actively moving all content out of the docs repo and into the CMS, for exactly this reason.

Definitely CMS will help as one of the reasons for slowness was conflicts in files that were edited by multiple people. 

I don't think it's a major problem per se, but the feedback loop (for frontend) when making changes is long in the website app by modern standards, especially considering you need to refresh the page to see changes on the templates. When working on big features, this adds up. That said I think any kind of decoupling (like the one you've outlined) will help.

> Well when you say wider group, who is that wider group? Our maintainers of web assets use Ruby currently. Sure, perhaps JS more generally is more widely known, but so is PHP :)

I see js developers as a wider group because most teams need frontend developers and smaller, fullstack JS apps (JAM stack apps, Node.js based static site generators) can be handled just by them. This is part of the reason why I think Node.js has been so widely adopted in many massive companies alongside Java instead of Ruby or PHP.

> Sure [...]

@mattheworiordan What do you think if the navigation and footer would live in a separate repo and be consumed in the same way docs are now, but by both docs and website? This respects that our current apps are Ruby/Rails and we can export just a template with JS/CSS. So the main piece of work is to add some scoped CSS/JS that would work in both places.

**Comment by mattheworiordan** [comment]
> What do you think if the navigation and footer would live in a separate repo

We are moving to mono-repo generally, because we want a PRs to encapsulate all changes across areas they affect.  Docs is sadly an exception because it's an open repo.  So I am not sure I see any advantage of having a separate repo, and it would definitely make it harder for example to add a page now that would require two PRs to be synchronised (think about the innocuous change made recently adding the Experts Network, which would have been two PRs, reviewed independently, then merged, tested again, and deployed).

> This respects that our current apps are Ruby/Rails and we can export just a template with JS/CSS. So the main piece of work is to add some scoped CSS/JS that would work in both places.

Conceptually happy with that idea.  I'm just not sure how it would work in practice.  Very open to your suggestions here.

**Comment by dpiatek** [comment]
> We are moving to mono-repo generally, because we want a PRs to encapsulate all changes across areas they affect.

I'm all for that! The ones I've worked with were great.

> Docs is sadly an exception because it's an open repo. So I am not sure I see any advantage of having a separate repo, and it would definitely make it harder for example to add a page now that would require two PRs to be synchronised (think about the innocuous change made recently adding the Experts Network, which would have been two PRs, reviewed independently, then merged, tested again, and deployed).

Agree another repo is not ideal ... !

But the more I think about sharing through HTTP, the more I think it will be a very fragile dependency and keeping it sync will be tricky (ie. I'd like not to add things to the website that will make think "If I modify this thing will it break something on the docs repo when it rebuilds? How will somebody then fix it?"). And to make it work we still need to encapsulate the HTML/CSS/JS which is easier before creating production bundles then after.
 
I still think the best solution would be for the docs to have its own (simpler) nav and footer and only get data/session from the website (ie. going with the spirit of [duplication is far cheaper than the wrong abstraction](https://www.sandimetz.com/blog/2016/1/20/the-wrong-abstraction)). Navigation components are notoriously hard to componentize because they usually contain so much logic, personalisation etc and the benefit of sharing one I think would be diminished for us.

**Comment by mattheworiordan** [comment]
Interesting to look at some other relevant peers and how they approach their docs.

# Algolia

URL: https://www.algolia.com/doc/
Tech: Unknown, repo not online

Hosted as part of the main site.  Completely different navigation system and components, focussed on docs.

# Stripe

URL: https://stripe.com/docs
Tech: Unknown, repo not online

Hosted as part of the main site.  Completely different navigation system and components, focussed on docs.

# Stripe

URL: https://www.twilio.com/docs
Tech: Unknown, repo not online

Hosted as part of the main site.  Completely different navigation system and components, focussed on docs.

# Netlify

URL: https://docs.netlify.com/
Tech: Unkown, but spikes at https://github.com/netlify/docs-spike and https://github.com/netlify/docsy-example

Hosted on a separate domain.  Completely different navigation system and components, focussed on docs.

# Gatsby

URL: https://www.gatsbyjs.org/docs/
Tech: Surprisingly built with Gatsby :)

Hosted on same domain, shares the same header, but otherwise quite different.  Like the "Edit this page" link, taking you to a Markdown file, https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/index.md

# Vercel

URL: https://vercel.com/docs
Tech: Next.js, https://github.com/zeit/docs

Hosted on the same domain, Completely different navigation system and components, focussed on docs.

# Auth0

URL: https://auth0.com/docs/
Tech: Not clear, but static site build, https://github.com/auth0/docs

Hosted on the same domain, Completely different navigation system and components, focussed on docs.
