### ISSUE TITLE
Update README instructions

### ISSUE THREAD

**Issue by MarkWoulfeAbly** [ably/docs#884]
Following the guide I ran into a number of issues which I feel we can address by updating the documentation:

1. Suggest Mac, there are a number of complications when trying to set up on Windows.
2. Remove deploying to website section, this is not purely for external use and can be moved into a confluence page.
3. Mention the need for Ruby 2.7.0, this is needed to run * `bundle install` to install the necessary gems, including `nanoc`
4. Remove Docker instructions while we work on fixing https://ably.atlassian.net/browse/WEB-383

TBC

**Comment by mattheworiordan** [comment]
Can you address this now @MarkWoulfeAbly?

**Comment by mattheworiordan** [comment]
Would you mind tagging issues as well please?
