### ISSUE TITLE
Update information on replicas in support articles to reflect the pricing page

### ISSUE THREAD

**Issue by gemmasheehan** [ably/docs#886]
https://support.ably.io/support/solutions/articles/3000029531 has out of date information regarding the number of replicas we guarantee to Self-Service and Business customers and over how many regions. 

<img width="1037" alt="Screenshot 2020-05-20 at 10 06 22" src="https://user-images.githubusercontent.com/49942150/82427912-a51fba00-9a81-11ea-98a1-dc0647dae089.png">
<img width="698" alt="Screenshot 2020-05-20 at 10 07 43" src="https://user-images.githubusercontent.com/49942150/82428013-c680a600-9a81-11ea-9684-cbbc266aa4f0.png">

**Comment by MarkWoulfeAbly** [comment]
Passed onto the support team.
