### ISSUE TITLE
Backend behavior inconsistent with RTL6g1b?

### ISSUE THREAD

**Issue by tcard** [ably/docs#90]
[RTL6g1b says](http://docs.ably.io/client-lib-development-guide/features/#RTL6g1b):

> (RTL6g1b) Ably will not assign a clientId upon receiving the Message. A test should assert that the clientId value is null for the Message when received

But, from a realtime client with the `clientId` set in `ClientOptions`  to `client_string`, I send this ProtocolMessage:

```json
{
  "msgSerial": 0,
  "messages": [
    {
      "data": "message"
    }
  ],
  "channel": "test",
  "action": 15
}
```

And get echoed back this one:

```json
{
  "action": 15,
  "id": "ks5y5ugW7t-0",
  "count": 7,
  "channel": "test",
  "channelSerial": "a2b1d70246585:0",
  "connectionId": "ks5y5ugW7t",
  "connectionSerial": 0,
  "timestamp": 1456338389811,
  "messages": [
    {
      "clientId": "client_string",
      "data": "message"
    }
  ]
}
```

So it seems that Ably _is_ assigning the `clientId` upon receiving the message.

What's wrong here?

**Comment by mattheworiordan** [comment]
This is a bug in the spec :(
I will review the docs now and issue a PR to resolve this.
Thanks for spotting @tcard
