### ISSUE TITLE
Ruby block code doesn't output correctly in quick start guide

### ISSUE THREAD

**Issue by owenpearson** [ably/docs#935]
The Ruby block code under the "[Recieving messages](https://www.ably.io/documentation/quick-start-guide#receiving-messages)" heading in the quick start guide is output as plain text with the Textile syntax left in. The markup that gets displayed is from lines 148-154 [here](https://github.com/ably/docs/blame/master/content/root/quick-start-guide.textile).

Below screenshot is from chrome 84.0.4147.105 on macOS Catalina 10.15.6.
<img width="812" alt="Screenshot 2020-08-10 at 12 33 22" src="https://user-images.githubusercontent.com/48608556/89785485-67777e00-db12-11ea-9906-ae00d42427b7.png">

**Comment by MarkWoulfeAbly** [comment]
Resolved in https://github.com/ably/docs/pull/937
