### ISSUE TITLE
Message ordering from history article / documentation

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#964]
See a [recent discussion with a customer](https://ably-real-time.slack.com/archives/CDLTXNZL2/p1599665979001300) on message history ordering.  Looking at our docs, and support solution articles, it appears we do not have documentation that sufficiently describes the behaviour of history in respect to ordering (the closest is https://support.ably.com/a/solutions/articles/3000044641).  We should create a support article for now, and later consider adding documentation for this.

---

Question:

> Is there any guarantee that messages received from the history API will be in order? It appears that one of our clients is getting messages from the history that are out of order according to their timestamps.

Our response:

> It depends what you mean by 'in order'.
> There is the order that the messages will have been received by a realtime client. But that will vary depending on what region the client is in. We preserve ordering for a given publisher on a given channel, but for example if two publishers in regions A and B publish messages 'a' and 'b' (respectively) approximately simultaneously, it's quite like that a subscriber in region A will see 'a' before 'b', and one in region B will see 'b' before 'a'.
> The ordering that history results are returned in is the ordering defined by the message timestamp which is assigned by the channel in the region that the message was published in. This means that history results - unlike realtime messages - are in the same order no matter where in the world you query them from. But  that order (which we call the canonical global order) may not be the same order as any client in any region actually received them in real time if they were subscribed to the channel.

> there are exceptions to that. One is recent messages (retrieved from live ephemeral storage rather than persisted); they will be in regional ordering, and then will mesh back into canonical global ordering from persisted storage (with a mechanism that prevents duplication & missing messages) when you paginate further back

> another exception is untilAttach, which is a point in a regional message stream, so results returned from an untilAttach query do not satisfy this

> That would explain it then, because we’re using untilAttach

> And this appears to be an issue when the client region is really far away from the publishing region, as well.

> so when using untilAttach the messages will be in the regional order of the region the client is in, because they have to mesh forwards into the live message stream at that point. You may well ask why we can't send them in CGO order and filter, and the answer is we plan to do that eventually, but that's pending on completely moving away from serially-incrementing channelSerials to a channelTimeserial to mark the point of attachment

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/DOC-202) by [Unito](https://www.unito.io)

**Comment by markcoxsmith** [comment]
Support article created: https://support.ably.com/a/solutions/articles/3000102264
