### ISSUE TITLE
Consistent about Ably section for all public Ably repos

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#967]
We have lots of public repos, from client SDKs (https://github.com/ably/ably-js) to docs (https://github.com/ably/docs) to load testing (https://github.com/ably/ably-boomer) to demos (https://github.com/ably/whiteboard).

We should review generic about Ably messaging that exists in all public repos that gives users context, explains what Ably does, etc.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/DOC-197) by [Unito](https://www.unito.io)

**Comment by tbedford** [comment]
@marklewin - this ties in with the work on reviewing READMEs and providing a README template. We should also look to see if we can improve README consistency, messaging etc across all repos.

**Comment by tbedford** [comment]
Sorry for barging in, but I really like the second option - that is a very nice summary. p.s. we should have a link to the docs page too - with link text something along the lines of "See the Ably documentation for further information.". :)
