### ISSUE TITLE
Deltas - not SEO optimized

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#972]
When searching for "deltas ably", the following comes up:

![screenshot_2020-10-07_06-29-50_am](https://user-images.githubusercontent.com/43789/95291131-c2092e00-0866-11eb-8ae5-312163f36fa6.png)

Issues are:

* [ ] Why is no description showing?
* [ ] The page title is not descriptive and should be.  How does this apply to other similar pages throughout?

┆Issue is synchronized with this [Jira Bug](https://ably.atlassian.net/browse/DOC-200) by [Unito](https://www.unito.io)
┆Attachments: <a href="https://ably.atlassian.net/secure/attachment/11587/Screenshot+2022-01-10+at+15.06.52.png">Screenshot 2022-01-10 at 15.06.52.png</a>

**Comment by kavalerov** [comment]
Unfortunately, it looks like this issue applies to other docs pages as well: 

<img width="1366" alt="Screenshot 2020-10-08 at 00 01 27" src="https://user-images.githubusercontent.com/1847904/95387577-9420f980-08f9-11eb-94ee-b1c665fe27cd.png">

<img width="1228" alt="Screenshot 2020-10-08 at 00 03 05" src="https://user-images.githubusercontent.com/1847904/95387614-a733c980-08f9-11eb-9a62-2e50cf510a64.png">

**Comment by kavalerov** [comment]
I think this is one more issue to address in the upcoming docs overhaul.
