### ISSUE TITLE
Improve the language used for instantiating ably classes

### ISSUE THREAD

**Issue by tiholic** [ably/docs#985]
"to instance the Rest" (or Realtime) is used in many places while it should be "to instantiate the Rest" (or Realtime)

ex: https://github.com/ably/docs/blame/main/content/rest/usage.textile#L47

grep: https://github.com/ably/docs/search?q=%22to+instance+the%22

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/DOC-206) by [Unito](https://www.unito.io)

**Comment by marklewin** [comment]
@paddybyers "Instance" can be and is used as a verb, but in "normal" English it means "to mention as an example". E.g. 

"The reporter instanced the case of an elderly man, who couldn't afford to pay his heating bill on his state pension".

I've only heard instance used in this context as a noun? E.g. "an object is an instance of its class". To actually create that instance, you "instantiate" it?
