### ISSUE TITLE
Realtime channel methods `publish` is messed up!

### ISSUE THREAD

**Issue by tiholic** [ably/docs#988]
The 2nd paragraph [in live docs](https://www.ably.io/documentation/realtime/channels#publish) for `java` should render:
```
Publish several messages on this channel. A listener may optionally be passed in to this call to be notified of success of the operation. If the channel is initialized (i.e. no attempt to attach has yet been made for this channel), then calling publish will implicitly attach the channel.
```
according to https://github.com/ably/docs/blame/main/content/realtime/channels.textile#L932 :
```textile
// content in textile
Publish several messages on this channel. A <span lang="default">callback</span><span lang="java">listener</span><span lang="ruby">block</span> may optionally be passed in to this call to be notified of success <span lang="default">or failure</span><span lang="ruby"></span> of the operation. <span lang="default">If the channel is @initialized@ (i.e. no attempt to attach has yet been made for this channel), then calling @publish@ will implicitly attach the channel.</span><span lang="jsall,ruby,swift">When publish is called with this client library, it "won't attempt to implicitly attach to the channel":#transient-publish.</span>
```
But it just renders:
```
Publish several messages on this channel. A listener may optionally be passed in to this call to be notified of success of the operation.
```

Not sure if the expected content to be rendered is appropriate for java. I believe this was unintentionally not-handled and as a side effect of this probable bug, the content was being rendered sensibly.

I guess the reason for this is due to bad parsing/interpretation of the span tags if used incorrectly.

Also the same 2nd paragraph with javascript `A may optionally be passed in to this...`, where as it should have `a callback may optionally be passed in to this...`:

![image](https://user-images.githubusercontent.com/14252381/99216601-0be91a80-27fc-11eb-8571-3a45f153c831.png)

Solution:
grouping the dynamic content in another `span` tag seems to solve this issue.
```textile
<span>A <span lang="default">callback</span><span lang="java">listener</span><span lang="ruby">block</span> may optionally be passed...</span>
```

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/DOC-209) by [Unito](https://www.unito.io/learn-more)

**Comment by SimonWoolf** [comment]
Thanks for reporting the issue! Sorry for the radio silence - we're in a bit of a transitory period at the moment as we have a new docs maintainer due to start at the beginning of december, so they should pick this up up soon after that.
