### ISSUE TITLE
Make sure that code samples exist for all parts of documentation that are supported by particular language

### ISSUE THREAD

**Issue by kavalerov** [ably/docs#990]
In cases when certain language doesn't have the support for particular feature yet, we should find a way to clearly document this. 

For example, we have Channel Params code samples only for JS and Node.js at the moment, but it is also supported in other SDK client libraries that conform to the V1.2 of the client library spec.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/DOC-210) by [Unito](https://www.unito.io)

**Comment by tbedford** [comment]
@kavalerov we should have a chat about this! :)

**Comment by kavalerov** [comment]
Agreed - please feel free to either arrange a call (or we can discuss in one of the recurring ones)
